package commands

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// thin aliases keep the install tests readable
var (
	osMkdirAll  = os.MkdirAll
	osReadFile  = os.ReadFile
	osWriteFile = os.WriteFile
)

var errFake = fmt.Errorf("tool exploded")

func specOf(t *testing.T, byrePath string, o InstallAppOptions) appInstall {
	t.Helper()
	a, err := resolveInstall(byrePath, o)
	if err != nil {
		t.Fatal(err)
	}
	return a
}

func TestDropletSourceBakesPathAndBox(t *testing.T) {
	src := deliverAppSource(specOf(t, "/Users/p/my tools/byre", InstallAppOptions{Box: "proj-abc"}))
	for _, want := range []string{
		`property byrePath : "/Users/p/my tools/byre"`,
		"--box 'proj-abc'",
		"on open droppedItems",
		"on run",
		"quoted form of POSIX path of f",   // dropped paths are quoted, not spliced
		"</dev/null",                       // drops run detached (no terminal needed)
		`tell application "Terminal"`,      // plain click opens the interactive beat
		"repeat until busy of t or waited", // wait for the run to START (close-race fix)
		"else if sawBusy then",             // never-went-busy is UNKNOWN: window stays open
		"repeat while busy of t",           // ...and watches the run,
		"do script cmd in front window",    // fresh-launch startup window reused (no stray second window)
		`set cmd to "clear; `,              // the dedicated window opens on the prompt, not shell noise
		"close (every window whose tty of selected tab is theTTY)", // closing on success
		"|| touch ", // failure flag keeps the window open
		"Generated by byre",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("droplet source missing %q", want)
		}
	}
}

func TestDropletSourceNoBox(t *testing.T) {
	if src := deliverAppSource(specOf(t, "/usr/local/bin/byre", InstallAppOptions{})); strings.Contains(src, "--box") {
		t.Fatal("no --box should be baked when none was given")
	}
}

func TestDropletSourceEscapesQuotes(t *testing.T) {
	src := deliverAppSource(specOf(t, `/odd/pa"th/byre`, InstallAppOptions{}))
	if !strings.Contains(src, `property byrePath : "/odd/pa\"th/byre"`) {
		t.Fatalf("byre path not AppleScript-escaped:\n%s", src)
	}
}

func TestQuickActionFiles(t *testing.T) {
	info, wflow := quickActionFiles(specOf(t, "/usr/local/bin/byre", InstallAppOptions{Box: "proj-x"}))
	if !strings.Contains(info, "<string>Deliver to Byre</string>") ||
		!strings.Contains(info, "public.item") {
		t.Fatalf("Info.plist wrong:\n%s", info)
	}
	for _, want := range []string{
		"com.apple.RunShellScript",
		xmlEscape(`'/usr/local/bin/byre' deliver --box 'proj-x' "$@" </dev/null`),
		"com.apple.Automator.servicesMenu",
	} {
		if !strings.Contains(wflow, want) {
			t.Errorf("document.wflow missing %q", want)
		}
	}
}

func TestDesktopEntry(t *testing.T) {
	entry := desktopEntry(specOf(t, "/home/p/.local/bin/byre", InstallAppOptions{}))
	for _, want := range []string{
		"# Generated by byre. Do not edit; re-run: byre deliver --install-app\n",
		"Name=Byre Deliver",
		"Exec=/home/p/.local/bin/byre deliver %F",
		"Terminal=false",
		"Icon=byre-deliver",
	} {
		if !strings.Contains(entry, want) {
			t.Errorf("desktop entry missing %q:\n%s", want, entry)
		}
	}
}

func TestDesktopEntryQuotesSpaceyPath(t *testing.T) {
	entry := desktopEntry(specOf(t, "/home/p/my tools/byre", InstallAppOptions{}))
	if !strings.Contains(entry, `Exec="/home/p/my tools/byre" deliver %F`) {
		t.Fatalf("spacey Exec path not quoted:\n%s", entry)
	}
}

func testPNG(t *testing.T, size int) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, size, size))
	img.Set(0, 0, color.RGBA{1, 2, 3, 255})
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func TestPackICNS(t *testing.T) {
	pngBytes := testPNG(t, 512)
	icns, err := packICNS(pngBytes)
	if err != nil {
		t.Fatal(err)
	}
	if string(icns[:4]) != "icns" {
		t.Fatalf("bad magic %q", icns[:4])
	}
	if got := binary.BigEndian.Uint32(icns[4:8]); int(got) != len(icns) {
		t.Fatalf("total length %d != %d", got, len(icns))
	}
	if string(icns[8:12]) != "ic09" { // 512 → ic09
		t.Fatalf("chunk type %q", icns[8:12])
	}
	if !bytes.Equal(icns[16:], pngBytes) {
		t.Fatal("PNG payload not verbatim")
	}
}

func TestPackICNSRejectsBadSizes(t *testing.T) {
	if _, err := packICNS(testPNG(t, 100)); err == nil || !strings.Contains(err.Error(), "must be 128, 256, 512, or 1024") {
		t.Fatalf("100px must be rejected by the size rule, got: %v", err)
	}
	if _, err := packICNS([]byte("not a png")); err == nil || !strings.Contains(err.Error(), "must be a PNG") {
		t.Fatalf("non-PNG must be rejected by the decode rule, got: %v", err)
	}
}

func TestEmbeddedIconPacks(t *testing.T) {
	// The committed asset must always be icns-packable — a bad swap-in
	// (wrong size, not PNG) fails here, not at a user's install.
	if _, err := packICNS(deliverIconPNG); err != nil {
		t.Fatalf("embedded icon does not pack: %v", err)
	}
	if _, err := packICNS(deliverIconSSHPNG); err != nil {
		t.Fatalf("embedded ssh icon does not pack: %v", err)
	}
}

func testDeps(t *testing.T, goos string) (installDeps, *[]string) {
	t.Helper()
	var calls []string
	return installDeps{
		goos: goos,
		home: t.TempDir(),
		exe:  "/fake/bin/byre",
		run: func(name string, args ...string) error {
			calls = append(calls, name+" "+strings.Join(args, " "))
			if name == "osacompile" {
				// The real tool creates the bundle; the fake mimics the
				// Resources layout the installer writes into.
				app := args[1]
				if err := osMkdirAll(app+"/Contents/Resources", 0o755); err != nil {
					return err
				}
			}
			return nil
		},
	}, &calls
}

func TestInstallDarwin(t *testing.T) {
	d, calls := testDeps(t, "darwin")
	s, out, errw := testStreams("", false)
	if err := installApp(s, InstallAppOptions{Box: "proj-x"}, d); err != nil {
		t.Fatal(err)
	}
	app := d.home + "/Applications/Byre Deliver.app"
	src, err := osReadFile(app + "/Contents/Resources/droplet.applescript")
	if err != nil || !strings.Contains(string(src), "Generated by byre") || !strings.Contains(string(src), "--box 'proj-x'") {
		t.Fatalf("bundle source wrong: %v %q", err, src)
	}
	if icns, err := osReadFile(app + "/Contents/Resources/droplet.icns"); err != nil || string(icns[:4]) != "icns" {
		t.Fatalf("icon not installed: %v", err)
	}
	joined := strings.Join(*calls, "\n")
	staged := d.home + "/Applications/.Byre Deliver.staged.app"
	if !strings.Contains(joined, "osacompile -o "+staged) ||
		!strings.Contains(joined, "codesign --force --deep --sign - "+staged) ||
		!strings.Contains(joined, "touch "+app) {
		t.Fatalf("tool calls wrong (assemble+sign staged, swap, touch final):\n%s", joined)
	}
	if wf, err := osReadFile(d.home + "/Library/Services/Deliver to Byre.workflow/Contents/document.wflow"); err != nil || !strings.Contains(string(wf), "byre") {
		t.Fatalf("quick action missing: %v", err)
	}
	// stdout carries exactly the installed paths.
	if lines := strings.Split(strings.TrimSpace(out.String()), "\n"); len(lines) != 2 ||
		!strings.HasSuffix(lines[0], "Byre Deliver.app") || !strings.HasSuffix(lines[1], ".workflow") {
		t.Fatalf("stdout = %q", out.String())
	}
	if !strings.Contains(errw.String(), "to uninstall") {
		t.Fatalf("no uninstall story: %q", errw.String())
	}
}

func TestInstallDarwinRegeneratesOwnRefusesForeign(t *testing.T) {
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	if err := installApp(s, InstallAppOptions{}, d); err != nil {
		t.Fatal(err)
	}
	// Second run over our own artifact: fine (regeneration).
	if err := installApp(s, InstallAppOptions{Box: "other-box"}, d); err != nil {
		t.Fatalf("regeneration refused: %v", err)
	}
	// A same-named app byre did NOT write: refused, not clobbered.
	marker := d.home + "/Applications/Byre Deliver.app/Contents/Resources/droplet.applescript"
	if err := osWriteFile(marker, []byte("something else entirely"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, InstallAppOptions{}, d); err == nil || !strings.Contains(err.Error(), "doesn't look byre-generated") {
		t.Fatalf("foreign app clobbered: err = %v", err)
	}
}

func TestInstallLinux(t *testing.T) {
	d, calls := testDeps(t, "linux")
	s, out, _ := testStreams("", false)
	if err := installApp(s, InstallAppOptions{}, d); err != nil {
		t.Fatal(err)
	}
	entry, err := osReadFile(d.home + "/.local/share/applications/byre-deliver.desktop")
	if err != nil || !strings.Contains(string(entry), "Exec=/fake/bin/byre deliver %F") {
		t.Fatalf("desktop entry wrong: %v %q", err, entry)
	}
	cfg, _, cfgErr := image.DecodeConfig(bytes.NewReader(deliverIconPNG))
	if cfgErr != nil {
		t.Fatal(cfgErr)
	}
	iconPath := fmt.Sprintf("%s/.local/share/icons/hicolor/%dx%d/apps/byre-deliver.png", d.home, cfg.Width, cfg.Height)
	if icon, err := osReadFile(iconPath); err != nil || len(icon) == 0 {
		t.Fatalf("icon missing: %v", err)
	}
	if len(*calls) != 0 {
		t.Fatalf("linux install should exec nothing: %v", *calls)
	}
	if !strings.Contains(out.String(), "byre-deliver.desktop") {
		t.Fatalf("stdout = %q", out.String())
	}
}

func TestInstallLinuxRefusesForeignEntry(t *testing.T) {
	d, _ := testDeps(t, "linux")
	s, _, _ := testStreams("", false)
	entry := d.home + "/.local/share/applications/byre-deliver.desktop"
	if err := osMkdirAll(d.home+"/.local/share/applications", 0o755); err != nil {
		t.Fatal(err)
	}
	if err := osWriteFile(entry, []byte("[Desktop Entry]\nName=Someone Else\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, InstallAppOptions{}, d); err == nil || !strings.Contains(err.Error(), "doesn't look byre-generated") {
		t.Fatalf("foreign entry clobbered: err = %v", err)
	}
}

func TestInstallDarwinOsacompileFailurePreservesOldApp(t *testing.T) {
	// regeneration must never destroy the working app when
	// assembly fails — compile staged, swap last.
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	if err := installApp(s, InstallAppOptions{}, d); err != nil {
		t.Fatal(err)
	}
	realRun := d.run
	d.run = func(name string, args ...string) error {
		if name == "osacompile" {
			return errFake
		}
		return realRun(name, args...)
	}
	if err := installApp(s, InstallAppOptions{}, d); err == nil {
		t.Fatal("expected the osacompile failure to surface")
	}
	marker := d.home + "/Applications/Byre Deliver.app/Contents/Resources/droplet.applescript"
	if src, err := osReadFile(marker); err != nil || !strings.Contains(string(src), "Generated by byre") {
		t.Fatalf("previous app was destroyed by a failed regeneration: %v", err)
	}
}

func TestInstallDarwinRefusesForeignQuickAction(t *testing.T) {
	// the Quick Action check must require the explicit
	// marker — a wflow merely containing 'byre', or an unreadable bundle,
	// is refused.
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	svc := d.home + "/Library/Services/Deliver to Byre.workflow"
	if err := osMkdirAll(svc+"/Contents", 0o755); err != nil {
		t.Fatal(err)
	}
	if err := osWriteFile(svc+"/Contents/document.wflow", []byte("someone's workflow that mentions byre"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, InstallAppOptions{}, d); err == nil || !strings.Contains(err.Error(), "doesn't look byre-generated") {
		t.Fatalf("foreign quick action not refused: %v", err)
	}
	// The refusal preflights BEFORE the app half runs: nothing may have
	// been installed or announced (half-committed installs
	// make the error unreliable and the retry misleading).
	if _, err := os.Stat(d.home + "/Applications/Byre Deliver.app"); !os.IsNotExist(err) {
		t.Fatalf("foreign quick action refusal must leave the app uninstalled: %v", err)
	}
	// Bundle present but wflow missing entirely: also refused.
	if err := osWriteFile(svc+"/Contents/document.wflow", nil, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, InstallAppOptions{}, d); err == nil {
		t.Fatal("marker-less bundle not refused")
	}
}

func TestDesktopEntryEscapesBoxArgument(t *testing.T) {
	// --box is arbitrary user input; spaces must not split
	// it and % must not become a field code.
	entry := desktopEntry(specOf(t, "/usr/bin/byre", InstallAppOptions{Box: "my box 100%"}))
	if !strings.Contains(entry, `--box "my box 100%%"`) {
		t.Fatalf("box not desktop-quoted:\n%s", entry)
	}
}

func TestQuickActionCarriesMarker(t *testing.T) {
	_, wflow := quickActionFiles(specOf(t, "/usr/bin/byre", InstallAppOptions{}))
	if !strings.Contains(wflow, "Generated by byre") {
		t.Fatal("document.wflow lacks the generated marker")
	}
}

func TestInstallDarwinRegenerationLeavesNoRemnants(t *testing.T) {
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	for i := 0; i < 2; i++ { // install, then regenerate
		if err := installApp(s, InstallAppOptions{}, d); err != nil {
			t.Fatal(err)
		}
	}
	for _, remnant := range []string{".Byre Deliver.staged.app", ".Byre Deliver.previous.app"} {
		if _, err := os.Stat(d.home + "/Applications/" + remnant); !os.IsNotExist(err) {
			t.Fatalf("%s left behind: %v", remnant, err)
		}
	}
}

func TestGeneratedArtifactsWidenPATH(t *testing.T) {
	// Field-found: Finder's sparse PATH hid Docker Desktop from byre —
	// both launchers must export the widened PATH to byre's children.
	src := deliverAppSource(specOf(t, "/usr/local/bin/byre", InstallAppOptions{}))
	if !strings.Contains(src, `PATH=\"$PATH:/usr/local/bin:/opt/homebrew/bin:$HOME/.local/bin\" `) {
		t.Fatalf("droplet lacks the PATH prefix:\n%s", src)
	}
	_, wflow := quickActionFiles(specOf(t, "/usr/local/bin/byre", InstallAppOptions{}))
	if !strings.Contains(wflow, xmlEscape(launchPATH)) {
		t.Fatalf("quick action lacks the PATH prefix:\n%s", wflow)
	}
}

func TestInstallLinuxWarnsExperimental(t *testing.T) {
	d, _ := testDeps(t, "linux")
	s, _, errw := testStreams("", false)
	if err := installApp(s, InstallAppOptions{}, d); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(errw.String(), "EXPERIMENTAL") {
		t.Fatalf("linux install must flag the graphical path as experimental: %q", errw.String())
	}
}

func TestGeneratorsBakeRemoteCommandAndLabel(t *testing.T) {
	a := specOf(t, "/usr/local/bin/byre", InstallAppOptions{
		SSH:        "ssh://u@h:2222",
		Box:        "b",
		Name:       "studio",
		RemoteByre: "/opt/byre",
	})
	src := deliverAppSource(a)
	for _, want := range []string{
		` deliver 'ssh://u@h:2222' --box 'b' --remote-byre '/opt/byre'`,
		`with title "Byre Deliver (studio)"`,
		"re-run: byre deliver --install-app 'ssh://u@h:2222' --box 'b' --name 'studio' --remote-byre '/opt/byre'",
		"Generated by byre",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("droplet missing %q", want)
		}
	}
	info, wflow := quickActionFiles(a)
	if !strings.Contains(info, "<string>Deliver to Byre (studio)</string>") {
		t.Fatalf("NSMenuItem unlabeled:\n%s", info)
	}
	wantCmd := xmlEscape(`'/usr/local/bin/byre' deliver 'ssh://u@h:2222' --box 'b' --remote-byre '/opt/byre' "$@" </dev/null`)
	if !strings.Contains(wflow, wantCmd) {
		t.Errorf("document.wflow missing baked command %q", wantCmd)
	}
	entry := desktopEntry(a)
	for _, want := range []string{
		"Name=Byre Deliver (studio)",
		"Icon=byre-deliver-ssh",
		"Exec=/usr/local/bin/byre deliver ssh://u@h:2222 --box b --remote-byre /opt/byre %F",
		"# Generated by byre. Do not edit; re-run: byre deliver --install-app 'ssh://u@h:2222' --box 'b' --name 'studio' --remote-byre '/opt/byre'",
	} {
		if !strings.Contains(entry, want) {
			t.Errorf("desktop entry missing %q:\n%s", want, entry)
		}
	}
}

func TestGeneratorsSanitizeHostileLabelInFilenamesNotDisplay(t *testing.T) {
	const label = "my host/a:b %x"
	a := specOf(t, "/usr/bin/byre", InstallAppOptions{Name: label})
	if a.fsLabel != "my host-a-b %x" {
		t.Fatalf("fsLabel = %q", a.fsLabel)
	}
	if a.slug != "my-host-a-b--x" {
		t.Fatalf("slug = %q", a.slug)
	}
	if a.darwinAppName() != "Byre Deliver (my host-a-b %x).app" {
		t.Fatalf("app name = %q", a.darwinAppName())
	}
	if a.linuxDesktopName() != "byre-deliver-my-host-a-b--x.desktop" {
		t.Fatalf("desktop name = %q", a.linuxDesktopName())
	}
	src := deliverAppSource(a)
	if !strings.Contains(src, `with title "Byre Deliver (my host/a:b %x)"`) {
		t.Fatalf("display title not intact:\n%s", src)
	}
	info, _ := quickActionFiles(a)
	if !strings.Contains(info, "<string>"+xmlEscape("Deliver to Byre ("+label+")")+"</string>") {
		t.Fatalf("NSMenuItem not intact:\n%s", info)
	}
	entry := desktopEntry(a)
	if !strings.Contains(entry, "Name=Byre Deliver (my host/a:b %x)") {
		t.Fatalf("desktop Name not intact:\n%s", entry)
	}
}

func TestGeneratorsNeutralizeStructuralLabelCharacters(t *testing.T) {
	// User text never rides an XML comment (a comment may not contain
	// "--" at all, and no escaping can fix that) — the rerun hint lives
	// in the shell script string, where a '>'-bearing name is entity-
	// escaped ordinary text.
	a := specOf(t, "/usr/bin/byre", InstallAppOptions{Name: "a-->b"})
	_, wflow := quickActionFiles(a)
	if strings.Contains(wflow, "a-->b") {
		t.Fatalf("raw '-->' survived into the wflow:\n%s", wflow)
	}
	if !strings.Contains(wflow, "a--&gt;b") {
		t.Fatalf("escaped rerun missing from the wflow command string:\n%s", wflow)
	}
	// Control characters are stripped from the name before it reaches
	// display strings — a newline would structurally break the .desktop
	// Name= line and the AppleScript title literals.
	a = specOf(t, "/usr/bin/byre", InstallAppOptions{Name: "stu\ndio"})
	if a.display != "Byre Deliver (studio)" {
		t.Fatalf("display = %q", a.display)
	}
	if entry := desktopEntry(a); !strings.Contains(entry, "Name=Byre Deliver (studio)\n") {
		t.Fatalf("desktop Name carries the control character:\n%s", entry)
	}
	if src := deliverAppSource(a); !strings.Contains(src, `--name 'studio'`) {
		t.Fatalf("rerun header should carry the stripped name:\n%s", src)
	}
}

func TestQuickActionCommentsNeverCarryDoubleHyphen(t *testing.T) {
	// XML comments must not contain "--" (strict well-formedness — a
	// plain rerun like 'byre deliver --install-app' already violates it),
	// so nothing rerun-shaped may land in one. The id token is hex for
	// the same reason.
	for _, o := range []InstallAppOptions{
		{},
		{Box: "proj-x"},
		{Name: "a-->b", Box: "b", SSH: "ssh://u@h", RemoteByre: "/opt/byre"},
	} {
		_, wflow := quickActionFiles(specOf(t, "/usr/bin/byre", o))
		for _, m := range regexp.MustCompile(`(?s)<!--(.*?)-->`).FindAllStringSubmatch(wflow, -1) {
			if strings.Contains(m[1], "--") {
				t.Errorf("XML comment carries '--' (%+v): %q", o, m[1])
			}
		}
	}
}

func TestInstallRefusesSanitizationCollision(t *testing.T) {
	// fsLabel/slug are many-to-one ('a/b' and 'a:b' both become 'a-b');
	// the second install must refuse, not treat the first as its own
	// regeneration — the artifact carries its label as an identity token.
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	if err := installApp(s, InstallAppOptions{Name: "a/b", Box: "first"}, d); err != nil {
		t.Fatal(err)
	}
	err := installApp(s, InstallAppOptions{Name: "a:b", Box: "second"}, d)
	if err == nil || !strings.Contains(err.Error(), `belongs to the install labeled "a/b"`) {
		t.Fatalf("collision not refused: %v", err)
	}
	src, rerr := osReadFile(d.home + "/Applications/Byre Deliver (a-b).app/Contents/Resources/droplet.applescript")
	if rerr != nil || !strings.Contains(string(src), "--box 'first'") {
		t.Fatalf("victim install mutated: %v %q", rerr, src)
	}
	// Same label again: regeneration, not a collision.
	if err := installApp(s, InstallAppOptions{Name: "a/b", Box: "third"}, d); err != nil {
		t.Fatalf("same-label regeneration refused: %v", err)
	}

	dl, _ := testDeps(t, "linux")
	if err := installApp(s, InstallAppOptions{Name: "a/b", Box: "first"}, dl); err != nil {
		t.Fatal(err)
	}
	err = installApp(s, InstallAppOptions{Name: "a:b", Box: "second"}, dl)
	if err == nil || !strings.Contains(err.Error(), `belongs to the install labeled "a/b"`) {
		t.Fatalf("linux collision not refused: %v", err)
	}
	entry, rerr := osReadFile(dl.home + "/.local/share/applications/byre-deliver-a-b.desktop")
	if rerr != nil || !strings.Contains(string(entry), "--box first") {
		t.Fatalf("linux victim mutated: %v %q", rerr, entry)
	}
}

func TestInstallDarwinLabeledPathsAndHiddenNames(t *testing.T) {
	d, calls := testDeps(t, "darwin")
	s, out, _ := testStreams("", false)
	o := InstallAppOptions{Name: "studio"}
	if err := installApp(s, o, d); err != nil {
		t.Fatal(err)
	}
	app := d.home + "/Applications/Byre Deliver (studio).app"
	wf := d.home + "/Library/Services/Deliver to Byre (studio).workflow"
	if _, err := osReadFile(app + "/Contents/Resources/droplet.applescript"); err != nil {
		t.Fatalf("labeled app missing: %v", err)
	}
	if _, err := osReadFile(wf + "/Contents/document.wflow"); err != nil {
		t.Fatalf("labeled workflow missing: %v", err)
	}
	staged := d.home + "/Applications/.Byre Deliver (studio).staged.app"
	joined := strings.Join(*calls, "\n")
	if !strings.Contains(joined, "osacompile -o "+staged) {
		t.Fatalf("labeled staged path not used:\n%s", joined)
	}
	a := specOf(t, d.exe, o)
	if a.darwinBackupName() != ".Byre Deliver (studio).previous.app" {
		t.Fatalf("backup name = %q", a.darwinBackupName())
	}
	if err := installApp(s, o, d); err != nil { // regenerate: backup used then removed
		t.Fatal(err)
	}
	for _, remnant := range []string{a.darwinStagedName(), a.darwinBackupName()} {
		if _, err := os.Stat(d.home + "/Applications/" + remnant); !os.IsNotExist(err) {
			t.Fatalf("%s left behind: %v", remnant, err)
		}
	}
	if !strings.Contains(out.String(), app) || !strings.Contains(out.String(), wf) {
		t.Fatalf("stdout missing labeled paths: %q", out.String())
	}
}

func TestInstallDarwinSSHIcon(t *testing.T) {
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	if err := installApp(s, InstallAppOptions{SSH: "ssh://far"}, d); err != nil {
		t.Fatal(err)
	}
	got, err := osReadFile(d.home + "/Applications/Byre Deliver (far).app/Contents/Resources/droplet.icns")
	if err != nil {
		t.Fatal(err)
	}
	want, err := packICNS(deliverIconSSHPNG)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Fatal("ssh install did not pack deliverIconSSHPNG")
	}
	local, err := packICNS(deliverIconPNG)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Equal(got, local) {
		t.Fatal("ssh icon is identical to the local icon")
	}
}

func TestInstallLinuxSSHIconAndEntry(t *testing.T) {
	d, _ := testDeps(t, "linux")
	s, _, _ := testStreams("", false)
	if err := installApp(s, InstallAppOptions{SSH: "ssh://far"}, d); err != nil {
		t.Fatal(err)
	}
	entry, err := osReadFile(d.home + "/.local/share/applications/byre-deliver-far.desktop")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(entry), "Name=Byre Deliver (far)") ||
		!strings.Contains(string(entry), "Icon=byre-deliver-ssh") ||
		!strings.Contains(string(entry), "Exec=/fake/bin/byre deliver ssh://far %F") {
		t.Fatalf("ssh desktop entry:\n%s", entry)
	}
	cfg, _, cfgErr := image.DecodeConfig(bytes.NewReader(deliverIconSSHPNG))
	if cfgErr != nil {
		t.Fatal(cfgErr)
	}
	iconPath := fmt.Sprintf("%s/.local/share/icons/hicolor/%dx%d/apps/byre-deliver-ssh.png", d.home, cfg.Width, cfg.Height)
	got, err := osReadFile(iconPath)
	if err != nil {
		t.Fatalf("ssh icon missing: %v", err)
	}
	if !bytes.Equal(got, deliverIconSSHPNG) {
		t.Fatal("ssh icon bytes differ from deliverIconSSHPNG")
	}
}

func TestInstallDarwinUnnamedAndLabeledCoexist(t *testing.T) {
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	if err := installApp(s, InstallAppOptions{Box: "local-box"}, d); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, InstallAppOptions{Name: "studio", Box: "named-box"}, d); err != nil {
		t.Fatal(err)
	}
	unnamedApp := d.home + "/Applications/Byre Deliver.app/Contents/Resources/droplet.applescript"
	namedApp := d.home + "/Applications/Byre Deliver (studio).app/Contents/Resources/droplet.applescript"
	unnamedWF := d.home + "/Library/Services/Deliver to Byre.workflow/Contents/document.wflow"
	namedWF := d.home + "/Library/Services/Deliver to Byre (studio).workflow/Contents/document.wflow"
	for _, p := range []string{unnamedApp, namedApp, unnamedWF, namedWF} {
		if _, err := osReadFile(p); err != nil {
			t.Fatalf("coexist missing %s: %v", p, err)
		}
	}
	if err := installApp(s, InstallAppOptions{Box: "local-box-2"}, d); err != nil {
		t.Fatal(err)
	}
	namedSrc, err := osReadFile(namedApp)
	if err != nil || !strings.Contains(string(namedSrc), "--box 'named-box'") {
		t.Fatalf("regenerating unnamed clobbered named: %v %q", err, namedSrc)
	}
	if _, err := osReadFile(namedWF); err != nil {
		t.Fatalf("named workflow gone: %v", err)
	}
	if err := installApp(s, InstallAppOptions{Name: "studio", Box: "named-box-2"}, d); err != nil {
		t.Fatal(err)
	}
	unnamedSrc, err := osReadFile(unnamedApp)
	if err != nil || !strings.Contains(string(unnamedSrc), "--box 'local-box-2'") {
		t.Fatalf("regenerating named clobbered unnamed: %v %q", err, unnamedSrc)
	}
}

func TestInstallLinuxUnnamedAndLabeledCoexist(t *testing.T) {
	d, _ := testDeps(t, "linux")
	s, _, _ := testStreams("", false)
	if err := installApp(s, InstallAppOptions{Box: "local-box"}, d); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, InstallAppOptions{Name: "studio", Box: "named-box"}, d); err != nil {
		t.Fatal(err)
	}
	unnamed := d.home + "/.local/share/applications/byre-deliver.desktop"
	named := d.home + "/.local/share/applications/byre-deliver-studio.desktop"
	if b, err := osReadFile(unnamed); err != nil || !strings.Contains(string(b), "--box local-box") {
		t.Fatalf("unnamed: %v %q", err, b)
	}
	if b, err := osReadFile(named); err != nil || !strings.Contains(string(b), "--box named-box") {
		t.Fatalf("named: %v %q", err, b)
	}
	if err := installApp(s, InstallAppOptions{Box: "local-box-2"}, d); err != nil {
		t.Fatal(err)
	}
	if b, err := osReadFile(named); err != nil || !strings.Contains(string(b), "--box named-box") {
		t.Fatalf("regenerating unnamed clobbered named: %v %q", err, b)
	}
}

func TestInstallDarwinRefusesForeignLabeledApp(t *testing.T) {
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	app := d.home + "/Applications/Byre Deliver (studio).app"
	marker := app + "/Contents/Resources/droplet.applescript"
	if err := osMkdirAll(filepath.Dir(marker), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := osWriteFile(marker, []byte("someone else's app"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, InstallAppOptions{Name: "studio"}, d); err == nil || !strings.Contains(err.Error(), "doesn't look byre-generated") {
		t.Fatalf("foreign labeled app clobbered: err = %v", err)
	}
	if b, err := osReadFile(marker); err != nil || string(b) != "someone else's app" {
		t.Fatalf("foreign labeled app was mutated: %v %q", err, b)
	}
}

func TestInstallNameEmptyAfterSanitization(t *testing.T) {
	d, _ := testDeps(t, "linux")
	s, _, _ := testStreams("", false)
	err := installApp(s, InstallAppOptions{Name: "..."}, d)
	if err == nil || !strings.Contains(err.Error(), "--name has no usable characters") {
		t.Fatalf("dots-only --name: %v", err)
	}
	err = installApp(s, InstallAppOptions{Name: "///"}, d)
	if err == nil || !strings.Contains(err.Error(), "--name has no usable characters") {
		t.Fatalf("slash-only --name: %v", err)
	}
	err = installApp(s, InstallAppOptions{Name: "\n\t"}, d)
	if err == nil || !strings.Contains(err.Error(), "--name has no usable characters") {
		t.Fatalf("controls-only --name: %v", err)
	}
}
