package commands

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
	"strings"
	"testing"
)

// thin aliases keep the install tests readable
var (
	osMkdirAll  = os.MkdirAll
	osReadFile  = os.ReadFile
	osWriteFile = os.WriteFile
)

var errFake = fmt.Errorf("tool exploded")

func TestDropletSourceBakesPathAndBox(t *testing.T) {
	src := dropletSource("/Users/p/my tools/byre", "proj-abc")
	for _, want := range []string{
		`property byrePath : "/Users/p/my tools/byre"`,
		"--box 'proj-abc'",
		"on open droppedItems",
		"on run",
		"quoted form of POSIX path of f",   // dropped paths are quoted, not spliced
		"</dev/null",                       // drops run detached (no terminal needed)
		`tell application "Terminal"`,      // plain click opens the interactive beat
		"repeat until busy of t or waited", // wait for the run to START (close-race fix)
		"else if sawBusy then",             // never-went-busy is UNKNOWN: window stays open
		"repeat while busy of t",           // ...and watches the run,
		"do script cmd in front window",    // fresh-launch startup window reused (no stray second window)
		`set cmd to "clear; `,              // the dedicated window opens on the prompt, not shell noise
		"close (every window whose tty of selected tab is theTTY)", // closing on success
		"|| touch ", // failure flag keeps the window open
		"Generated by byre",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("droplet source missing %q", want)
		}
	}
}

func TestDropletSourceNoBox(t *testing.T) {
	if src := dropletSource("/usr/local/bin/byre", ""); strings.Contains(src, "--box") {
		t.Fatal("no --box should be baked when none was given")
	}
}

func TestDropletSourceEscapesQuotes(t *testing.T) {
	src := dropletSource(`/odd/pa"th/byre`, "")
	if !strings.Contains(src, `property byrePath : "/odd/pa\"th/byre"`) {
		t.Fatalf("byre path not AppleScript-escaped:\n%s", src)
	}
}

func TestQuickActionFiles(t *testing.T) {
	info, wflow := quickActionFiles("/usr/local/bin/byre", "proj-x")
	if !strings.Contains(info, "<string>Deliver to Byre</string>") ||
		!strings.Contains(info, "public.item") {
		t.Fatalf("Info.plist wrong:\n%s", info)
	}
	for _, want := range []string{
		"com.apple.RunShellScript",
		xmlEscape(`'/usr/local/bin/byre' deliver --box 'proj-x' "$@" </dev/null`),
		"com.apple.Automator.servicesMenu",
	} {
		if !strings.Contains(wflow, want) {
			t.Errorf("document.wflow missing %q", want)
		}
	}
}

func TestDesktopEntry(t *testing.T) {
	entry := desktopEntry("/home/p/.local/bin/byre", "")
	for _, want := range []string{
		"Name=Byre Deliver",
		"Exec=/home/p/.local/bin/byre deliver %F",
		"Terminal=false",
		"Icon=byre-deliver",
	} {
		if !strings.Contains(entry, want) {
			t.Errorf("desktop entry missing %q:\n%s", want, entry)
		}
	}
}

func TestDesktopEntryQuotesSpaceyPath(t *testing.T) {
	entry := desktopEntry("/home/p/my tools/byre", "")
	if !strings.Contains(entry, `Exec="/home/p/my tools/byre" deliver %F`) {
		t.Fatalf("spacey Exec path not quoted:\n%s", entry)
	}
}

func testPNG(t *testing.T, size int) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, size, size))
	img.Set(0, 0, color.RGBA{1, 2, 3, 255})
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func TestPackICNS(t *testing.T) {
	pngBytes := testPNG(t, 512)
	icns, err := packICNS(pngBytes)
	if err != nil {
		t.Fatal(err)
	}
	if string(icns[:4]) != "icns" {
		t.Fatalf("bad magic %q", icns[:4])
	}
	if got := binary.BigEndian.Uint32(icns[4:8]); int(got) != len(icns) {
		t.Fatalf("total length %d != %d", got, len(icns))
	}
	if string(icns[8:12]) != "ic09" { // 512 → ic09
		t.Fatalf("chunk type %q", icns[8:12])
	}
	if !bytes.Equal(icns[16:], pngBytes) {
		t.Fatal("PNG payload not verbatim")
	}
}

func TestPackICNSRejectsBadSizes(t *testing.T) {
	if _, err := packICNS(testPNG(t, 100)); err == nil {
		t.Fatal("100px should be rejected")
	}
	if _, err := packICNS([]byte("not a png")); err == nil {
		t.Fatal("non-PNG should be rejected")
	}
}

func TestEmbeddedIconPacks(t *testing.T) {
	// The committed asset must always be icns-packable — a bad swap-in
	// (wrong size, not PNG) fails here, not at a user's install.
	if _, err := packICNS(deliverIconPNG); err != nil {
		t.Fatalf("embedded icon does not pack: %v", err)
	}
}

func testDeps(t *testing.T, goos string) (installDeps, *[]string) {
	t.Helper()
	var calls []string
	return installDeps{
		goos: goos,
		home: t.TempDir(),
		exe:  "/fake/bin/byre",
		run: func(name string, args ...string) error {
			calls = append(calls, name+" "+strings.Join(args, " "))
			if name == "osacompile" {
				// The real tool creates the bundle; the fake mimics the
				// Resources layout the installer writes into.
				app := args[1]
				if err := osMkdirAll(app+"/Contents/Resources", 0o755); err != nil {
					return err
				}
			}
			return nil
		},
	}, &calls
}

func TestInstallDarwin(t *testing.T) {
	d, calls := testDeps(t, "darwin")
	s, out, errw := testStreams("", false)
	if err := installApp(s, "proj-x", d); err != nil {
		t.Fatal(err)
	}
	app := d.home + "/Applications/Byre Deliver.app"
	src, err := osReadFile(app + "/Contents/Resources/droplet.applescript")
	if err != nil || !strings.Contains(string(src), "Generated by byre") || !strings.Contains(string(src), "--box 'proj-x'") {
		t.Fatalf("bundle source wrong: %v %q", err, src)
	}
	if icns, err := osReadFile(app + "/Contents/Resources/droplet.icns"); err != nil || string(icns[:4]) != "icns" {
		t.Fatalf("icon not installed: %v", err)
	}
	joined := strings.Join(*calls, "\n")
	staged := d.home + "/Applications/.Byre Deliver.staged.app"
	if !strings.Contains(joined, "osacompile -o "+staged) ||
		!strings.Contains(joined, "codesign --force --deep --sign - "+staged) ||
		!strings.Contains(joined, "touch "+app) {
		t.Fatalf("tool calls wrong (assemble+sign staged, swap, touch final):\n%s", joined)
	}
	if wf, err := osReadFile(d.home + "/Library/Services/Deliver to Byre.workflow/Contents/document.wflow"); err != nil || !strings.Contains(string(wf), "byre") {
		t.Fatalf("quick action missing: %v", err)
	}
	// stdout carries exactly the installed paths.
	if lines := strings.Split(strings.TrimSpace(out.String()), "\n"); len(lines) != 2 ||
		!strings.HasSuffix(lines[0], "Byre Deliver.app") || !strings.HasSuffix(lines[1], ".workflow") {
		t.Fatalf("stdout = %q", out.String())
	}
	if !strings.Contains(errw.String(), "to uninstall") {
		t.Fatalf("no uninstall story: %q", errw.String())
	}
}

func TestInstallDarwinRegeneratesOwnRefusesForeign(t *testing.T) {
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	if err := installApp(s, "", d); err != nil {
		t.Fatal(err)
	}
	// Second run over our own artifact: fine (regeneration).
	if err := installApp(s, "other-box", d); err != nil {
		t.Fatalf("regeneration refused: %v", err)
	}
	// A same-named app byre did NOT write: refused, not clobbered.
	marker := d.home + "/Applications/Byre Deliver.app/Contents/Resources/droplet.applescript"
	if err := osWriteFile(marker, []byte("something else entirely"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, "", d); err == nil || !strings.Contains(err.Error(), "doesn't look byre-generated") {
		t.Fatalf("foreign app clobbered: err = %v", err)
	}
}

func TestInstallLinux(t *testing.T) {
	d, calls := testDeps(t, "linux")
	s, out, _ := testStreams("", false)
	if err := installApp(s, "", d); err != nil {
		t.Fatal(err)
	}
	entry, err := osReadFile(d.home + "/.local/share/applications/byre-deliver.desktop")
	if err != nil || !strings.Contains(string(entry), "Exec=/fake/bin/byre deliver %F") {
		t.Fatalf("desktop entry wrong: %v %q", err, entry)
	}
	cfg, _, cfgErr := image.DecodeConfig(bytes.NewReader(deliverIconPNG))
	if cfgErr != nil {
		t.Fatal(cfgErr)
	}
	iconPath := fmt.Sprintf("%s/.local/share/icons/hicolor/%dx%d/apps/byre-deliver.png", d.home, cfg.Width, cfg.Height)
	if icon, err := osReadFile(iconPath); err != nil || len(icon) == 0 {
		t.Fatalf("icon missing: %v", err)
	}
	if len(*calls) != 0 {
		t.Fatalf("linux install should exec nothing: %v", *calls)
	}
	if !strings.Contains(out.String(), "byre-deliver.desktop") {
		t.Fatalf("stdout = %q", out.String())
	}
}

func TestInstallLinuxRefusesForeignEntry(t *testing.T) {
	d, _ := testDeps(t, "linux")
	s, _, _ := testStreams("", false)
	entry := d.home + "/.local/share/applications/byre-deliver.desktop"
	if err := osMkdirAll(d.home+"/.local/share/applications", 0o755); err != nil {
		t.Fatal(err)
	}
	if err := osWriteFile(entry, []byte("[Desktop Entry]\nName=Someone Else\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, "", d); err == nil || !strings.Contains(err.Error(), "doesn't look byre-generated") {
		t.Fatalf("foreign entry clobbered: err = %v", err)
	}
}

func TestInstallDarwinOsacompileFailurePreservesOldApp(t *testing.T) {
	// Review finding: regeneration must never destroy the working app when
	// assembly fails — compile staged, swap last.
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	if err := installApp(s, "", d); err != nil {
		t.Fatal(err)
	}
	realRun := d.run
	d.run = func(name string, args ...string) error {
		if name == "osacompile" {
			return errFake
		}
		return realRun(name, args...)
	}
	if err := installApp(s, "", d); err == nil {
		t.Fatal("expected the osacompile failure to surface")
	}
	marker := d.home + "/Applications/Byre Deliver.app/Contents/Resources/droplet.applescript"
	if src, err := osReadFile(marker); err != nil || !strings.Contains(string(src), "Generated by byre") {
		t.Fatalf("previous app was destroyed by a failed regeneration: %v", err)
	}
}

func TestInstallDarwinRefusesForeignQuickAction(t *testing.T) {
	// Review finding: the Quick Action check must require the explicit
	// marker — a wflow merely containing 'byre', or an unreadable bundle,
	// is refused.
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	svc := d.home + "/Library/Services/Deliver to Byre.workflow"
	if err := osMkdirAll(svc+"/Contents", 0o755); err != nil {
		t.Fatal(err)
	}
	if err := osWriteFile(svc+"/Contents/document.wflow", []byte("someone's workflow that mentions byre"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, "", d); err == nil || !strings.Contains(err.Error(), "doesn't look byre-generated") {
		t.Fatalf("foreign quick action not refused: %v", err)
	}
	// The refusal preflights BEFORE the app half runs: nothing may have
	// been installed or announced (external review: half-committed installs
	// make the error unreliable and the retry misleading).
	if _, err := os.Stat(d.home + "/Applications/Byre Deliver.app"); !os.IsNotExist(err) {
		t.Fatalf("foreign quick action refusal must leave the app uninstalled: %v", err)
	}
	// Bundle present but wflow missing entirely: also refused.
	if err := osWriteFile(svc+"/Contents/document.wflow", nil, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := installApp(s, "", d); err == nil {
		t.Fatal("marker-less bundle not refused")
	}
}

func TestDesktopEntryEscapesBoxArgument(t *testing.T) {
	// Review finding: --box is arbitrary user input; spaces must not split
	// it and % must not become a field code.
	entry := desktopEntry("/usr/bin/byre", "my box 100%")
	if !strings.Contains(entry, `--box "my box 100%%"`) {
		t.Fatalf("box not desktop-quoted:\n%s", entry)
	}
}

func TestQuickActionCarriesMarker(t *testing.T) {
	_, wflow := quickActionFiles("/usr/bin/byre", "")
	if !strings.Contains(wflow, "Generated by byre") {
		t.Fatal("document.wflow lacks the generated marker")
	}
}

func TestInstallDarwinRegenerationLeavesNoRemnants(t *testing.T) {
	d, _ := testDeps(t, "darwin")
	s, _, _ := testStreams("", false)
	for i := 0; i < 2; i++ { // install, then regenerate
		if err := installApp(s, "", d); err != nil {
			t.Fatal(err)
		}
	}
	for _, remnant := range []string{".Byre Deliver.staged.app", ".Byre Deliver.previous.app"} {
		if _, err := os.Stat(d.home + "/Applications/" + remnant); !os.IsNotExist(err) {
			t.Fatalf("%s left behind: %v", remnant, err)
		}
	}
}

func TestGeneratedArtifactsWidenPATH(t *testing.T) {
	// Field-found: Finder's sparse PATH hid Docker Desktop from byre —
	// both launchers must export the widened PATH to byre's children.
	src := dropletSource("/usr/local/bin/byre", "")
	if !strings.Contains(src, `PATH=\"$PATH:/usr/local/bin:/opt/homebrew/bin:$HOME/.local/bin\" `) {
		t.Fatalf("droplet lacks the PATH prefix:\n%s", src)
	}
	_, wflow := quickActionFiles("/usr/local/bin/byre", "")
	if !strings.Contains(wflow, xmlEscape(launchPATH)) {
		t.Fatalf("quick action lacks the PATH prefix:\n%s", wflow)
	}
}

func TestInstallLinuxWarnsExperimental(t *testing.T) {
	d, _ := testDeps(t, "linux")
	s, _, errw := testStreams("", false)
	if err := installApp(s, "", d); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(errw.String(), "EXPERIMENTAL") {
		t.Fatalf("linux install must flag the graphical path as experimental: %q", errw.String())
	}
}
