package commands

import (
	"bytes"
	"fmt"
	"image"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/pjlsergeant/byre/internal/hostopen"
)

// generatedMarker is the phrase every generated artifact carries; only
// artifacts carrying it are ever replaced by regeneration.
const generatedMarker = "Generated by byre"

// installDeps are the host seams for --install-app, injectable for tests.
type installDeps struct {
	goos string
	home string
	exe  string // absolute path of the running byre binary
	run  func(name string, args ...string) error
}

// errNotByreGenerated refuses to overwrite an install-app artifact byre
// cannot recognize as its own: the user's file, the user's call.
func errNotByreGenerated(path string) error {
	return fmt.Errorf("%s exists and doesn't look byre-generated — remove it yourself and re-run", path)
}

func realInstallDeps() (installDeps, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return installDeps{}, fmt.Errorf("resolving home: %w", err)
	}
	exe, err := os.Executable()
	if err != nil {
		return installDeps{}, fmt.Errorf("resolving the byre binary path: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}
	return installDeps{
		goos: runtime.GOOS,
		home: home,
		exe:  exe,
		run: func(name string, args ...string) error {
			out, err := exec.Command(name, args...).CombinedOutput()
			if err != nil {
				return fmt.Errorf("%s: %s: %s", name, err, strings.TrimSpace(string(out)))
			}
			return nil
		},
	}, nil
}

// InstallApp materializes the deliver app (ADR 0021): the "Byre Deliver"
// drag-target app + "Deliver to Byre" Quick Action on macOS, the .desktop entry on
// Linux. Idempotent regeneration of byre's OWN artifacts: an existing
// artifact is only replaced when it carries the generated marker — a
// same-named thing byre didn't write is refused, not clobbered.
func InstallApp(s Streams, box string) error {
	deps, err := realInstallDeps()
	if err != nil {
		return err
	}
	return installApp(s, box, deps)
}

func installApp(s Streams, box string, d installDeps) error {
	switch d.goos {
	case "darwin":
		return installDarwin(s, box, d)
	default:
		return installLinux(s, box, d)
	}
}

func installDarwin(s Streams, box string, d installDeps) error {
	appDir := filepath.Join(d.home, "Applications")
	appPath := filepath.Join(appDir, "Byre Deliver.app")
	if err := hostopen.PlainMkdirAll(appDir, 0o755, hostopen.HostUserOwned); err != nil {
		return err
	}
	source := deliverAppSource(d.exe, box)

	// Regenerate only what byre wrote: the shipped source inside the bundle
	// is the marker. A same-named app WITHOUT it — or one whose state can't
	// even be established — is refused, never clobbered.
	marker := filepath.Join(appPath, "Contents", "Resources", "droplet.applescript")
	appExists := false
	switch _, err := hostopen.PlainStat(appPath, hostopen.HostUserOwned); {
	case err == nil:
		appExists = true
		if prev, err := hostopen.PlainReadFile(marker, hostopen.HostUserOwned); err != nil || !strings.Contains(string(prev), generatedMarker) {
			return errNotByreGenerated(appPath)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("checking %s: %w", appPath, err)
	}

	// Preflight the Quick Action destination BEFORE mutating the app: a
	// foreign workflow at its path refuses the whole install up front,
	// instead of surfacing after the app half was already committed and
	// announced (the failed command had half-happened,
	// making the error unreliable to interpret and the retry misleading).
	svcPath := filepath.Join(d.home, "Library", "Services", "Deliver to Byre.workflow")
	wflowPath := filepath.Join(svcPath, "Contents", "document.wflow")
	switch _, err := hostopen.PlainStat(svcPath, hostopen.HostUserOwned); {
	case err == nil:
		if prev, err := hostopen.PlainReadFile(wflowPath, hostopen.HostUserOwned); err != nil || !strings.Contains(string(prev), generatedMarker) {
			return errNotByreGenerated(svcPath)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("checking %s: %w", svcPath, err)
	}

	srcDir, err := hostopen.PlainMkdirTemp("", "byre-deliver-app-", hostopen.ByreCreated)
	if err != nil {
		return err
	}
	defer hostopen.PlainRemoveAll(srcDir, hostopen.ByreCreated)
	srcPath := filepath.Join(srcDir, "droplet.applescript")
	if err := hostopen.PlainWriteFile(srcPath, []byte(source), 0o644, hostopen.ByreCreated); err != nil {
		return err
	}
	// Assemble into a STAGED bundle first: a broken osacompile, bad disk, or
	// malformed source must never destroy the working app already installed.
	// Same parent dir, so the final swap is one rename.
	staged := filepath.Join(appDir, ".Byre Deliver.staged.app")
	_ = hostopen.PlainRemoveAll(staged, hostopen.HostUserOwned)
	// osacompile assembles the bundle from Apple's signed applet stub — the
	// whole "compile": no toolchain, no network, milliseconds (ADR 0021).
	if err := d.run("osacompile", "-o", staged, srcPath); err != nil {
		_ = hostopen.PlainRemoveAll(staged, hostopen.HostUserOwned)
		return fmt.Errorf("assembling the app (osacompile): %w", err)
	}
	// Ship the readable source in the bundle — the artifact stays inspectable.
	if err := hostopen.PlainWriteFile(filepath.Join(staged, "Contents", "Resources", "droplet.applescript"), []byte(source), 0o644, hostopen.ByreCreated); err != nil {
		_ = hostopen.PlainRemoveAll(staged, hostopen.ByreCreated)
		return err
	}
	// Icon: overwrite the stub's droplet/applet icns with ours.
	if icns, err := packICNS(deliverIconPNG); err == nil {
		for _, name := range []string{"droplet.icns", "applet.icns"} {
			_ = hostopen.PlainWriteFile(filepath.Join(staged, "Contents", "Resources", name), icns, 0o644, hostopen.ByreCreated)
		}
	} else {
		fmt.Fprintf(s.Err, "byre: warning: icon skipped (%v)\n", err)
	}
	// Overwriting the resources above invalidated the signature the applet stub
	// arrived with (osacompile assembles from Apple's signed stub). Re-sign ad-hoc
	// -- no certificate involved -- so macOS is not asked to launch a bundle whose
	// signature is present but broken, which is worse off than an unsigned one.
	if err := d.run("codesign", "--force", "--deep", "--sign", "-", staged); err != nil {
		fmt.Fprintf(s.Err, "byre: warning: ad-hoc codesign failed (%v) — the app usually still runs; if macOS refuses it, this is why\n", err)
	}
	// The swap, with the old app held as a restorable backup until the new
	// one is actually in place — no window where a rename failure leaves
	// NEITHER bundle installed.
	if appExists {
		backup := filepath.Join(appDir, ".Byre Deliver.previous.app")
		_ = hostopen.PlainRemoveAll(backup, hostopen.HostUserOwned)
		if err := hostopen.PlainRename(appPath, backup, hostopen.HostUserOwned); err != nil {
			_ = hostopen.PlainRemoveAll(staged, hostopen.ByreCreated)
			return fmt.Errorf("setting the old app aside: %w", err)
		}
		if err := hostopen.PlainRename(staged, appPath, hostopen.HostUserOwned); err != nil {
			_ = hostopen.PlainRemoveAll(staged, hostopen.ByreCreated)
			if rerr := hostopen.PlainRename(backup, appPath, hostopen.HostUserOwned); rerr != nil {
				// The one truly bad outcome: say exactly where the working
				// app still lives instead of claiming a restore that failed.
				return fmt.Errorf("installing the assembled app failed (%v) AND restoring the old one failed (%v) — your previous app is intact at %s; rename it back by hand", err, rerr, backup)
			}
			return fmt.Errorf("installing the assembled app (old app restored): %w", err)
		}
		if err := hostopen.PlainRemoveAll(backup, hostopen.HostUserOwned); err != nil {
			fmt.Fprintf(s.Err, "byre: warning: could not remove the old app's backup at %s (%v) — delete it yourself\n", backup, err)
		}
	} else if err := hostopen.PlainRename(staged, appPath, hostopen.HostUserOwned); err != nil {
		_ = hostopen.PlainRemoveAll(staged, hostopen.ByreCreated)
		return fmt.Errorf("installing the assembled app: %w", err)
	}
	_ = d.run("touch", appPath) // nudge Finder's icon cache
	fmt.Fprintf(s.Out, "%s\n", appPath)
	fmt.Fprintf(s.Err, "byre: installed the deliver app — drag it to the Dock, drop files on it, or open it to deliver the clipboard\n")

	// The Finder Quick Action (right-click → Deliver to Byre). Ownership was
	// preflighted above, before the app was touched; regeneration is gated
	// on the explicit generated marker there.
	info, wflow := quickActionFiles(d.exe, box)
	if err := hostopen.PlainMkdirAll(filepath.Join(svcPath, "Contents"), 0o755, hostopen.HostUserOwned); err != nil {
		return err
	}
	if err := hostopen.PlainWriteFile(filepath.Join(svcPath, "Contents", "Info.plist"), []byte(info), 0o644, hostopen.HostUserOwned); err != nil {
		return err
	}
	if err := hostopen.PlainWriteFile(wflowPath, []byte(wflow), 0o644, hostopen.HostUserOwned); err != nil {
		return err
	}
	fmt.Fprintf(s.Out, "%s\n", svcPath)
	fmt.Fprintf(s.Err, "byre: installed the Quick Action — right-click files in Finder → Quick Actions → Deliver to Byre\n")
	fmt.Fprintf(s.Err, "byre: first use asks macOS permission prompts once (Automation/notifications) — that's expected\n")
	fmt.Fprintf(s.Err, "byre: to uninstall: delete the two paths above\n")
	fmt.Fprintf(s.Err, "byre: to update (byre moved, new --box): re-run 'byre deliver --install-app'\n")
	return nil
}

func installLinux(s Streams, box string, d installDeps) error {
	appsDir := filepath.Join(d.home, ".local", "share", "applications")
	entryPath := filepath.Join(appsDir, "byre-deliver.desktop")
	switch prev, err := hostopen.PlainReadFile(entryPath, hostopen.HostUserOwned); {
	case err == nil:
		if !strings.Contains(string(prev), generatedMarker) {
			return errNotByreGenerated(entryPath)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("checking %s: %w", entryPath, err)
	}
	if err := hostopen.PlainMkdirAll(appsDir, 0o755, hostopen.HostUserOwned); err != nil {
		return err
	}
	if err := hostopen.PlainWriteFile(entryPath, []byte(desktopEntry(d.exe, box)), 0o644, hostopen.HostUserOwned); err != nil {
		return err
	}
	fmt.Fprintf(s.Out, "%s\n", entryPath)

	// The icon lands in the hicolor theme at its actual size.
	if cfg, _, err := image.DecodeConfig(bytes.NewReader(deliverIconPNG)); err == nil {
		iconDir := filepath.Join(d.home, ".local", "share", "icons", "hicolor",
			fmt.Sprintf("%dx%d", cfg.Width, cfg.Height), "apps")
		if err := hostopen.PlainMkdirAll(iconDir, 0o755, hostopen.HostUserOwned); err == nil {
			iconPath := filepath.Join(iconDir, "byre-deliver.png")
			if err := hostopen.PlainWriteFile(iconPath, deliverIconPNG, 0o644, hostopen.HostUserOwned); err == nil {
				fmt.Fprintf(s.Out, "%s\n", iconPath)
			}
		}
	}
	fmt.Fprintf(s.Err, "byre: installed the deliver launcher — drag files onto it in your app grid/dock\n")
	fmt.Fprintf(s.Err, "byre: NOTE — the Linux graphical path (dropping files on the launcher, the\n")
	fmt.Fprintf(s.Err, "byre:   picker dialog, notifications) is EXPERIMENTAL and unverified across\n")
	fmt.Fprintf(s.Err, "byre:   desktop environments; some don't support launcher drops at all. The\n")
	fmt.Fprintf(s.Err, "byre:   'byre deliver <file>' terminal flow is the supported path. Reports welcome.\n")
	fmt.Fprintf(s.Err, "byre: to uninstall: delete the paths above\n")
	fmt.Fprintf(s.Err, "byre: to update (byre moved, new --box): re-run 'byre deliver --install-app'\n")
	return nil
}
