package commands

import (
	"bytes"
	"encoding/binary"
	"image"
	"image/color"
	"image/png"
	"strings"
	"testing"
)

func TestDropletSourceBakesPathAndBox(t *testing.T) {
	src := dropletSource("/Users/p/my tools/byre", "proj-abc")
	for _, want := range []string{
		`property byrePath : "/Users/p/my tools/byre"`,
		"--box 'proj-abc'",
		"on open droppedItems",
		"on run",
		"quoted form of POSIX path of f", // dropped paths are quoted, not spliced
		"</dev/null",                     // detached stdin: no-arg opens read the clipboard
		"Generated by byre",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("droplet source missing %q", want)
		}
	}
}

func TestDropletSourceNoBox(t *testing.T) {
	if src := dropletSource("/usr/local/bin/byre", ""); strings.Contains(src, "--box") {
		t.Fatal("no --box should be baked when none was given")
	}
}

func TestDropletSourceEscapesQuotes(t *testing.T) {
	src := dropletSource(`/odd/pa"th/byre`, "")
	if !strings.Contains(src, `property byrePath : "/odd/pa\"th/byre"`) {
		t.Fatalf("byre path not AppleScript-escaped:\n%s", src)
	}
}

func TestQuickActionFiles(t *testing.T) {
	info, wflow := quickActionFiles("/usr/local/bin/byre", "proj-x")
	if !strings.Contains(info, "<string>Deliver to Byre</string>") ||
		!strings.Contains(info, "public.item") {
		t.Fatalf("Info.plist wrong:\n%s", info)
	}
	for _, want := range []string{
		"com.apple.RunShellScript",
		xmlEscape(`'/usr/local/bin/byre' deliver --box 'proj-x' "$@" </dev/null`),
		"com.apple.Automator.servicesMenu",
	} {
		if !strings.Contains(wflow, want) {
			t.Errorf("document.wflow missing %q", want)
		}
	}
}

func TestDesktopEntry(t *testing.T) {
	entry := desktopEntry("/home/p/.local/bin/byre", "")
	for _, want := range []string{
		"Name=Byre Deliver",
		"Exec=/home/p/.local/bin/byre deliver %F",
		"Terminal=false",
		"Icon=byre-deliver",
	} {
		if !strings.Contains(entry, want) {
			t.Errorf("desktop entry missing %q:\n%s", want, entry)
		}
	}
}

func TestDesktopEntryQuotesSpaceyPath(t *testing.T) {
	entry := desktopEntry("/home/p/my tools/byre", "")
	if !strings.Contains(entry, `Exec="/home/p/my tools/byre" deliver %F`) {
		t.Fatalf("spacey Exec path not quoted:\n%s", entry)
	}
}

func testPNG(t *testing.T, size int) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, size, size))
	img.Set(0, 0, color.RGBA{1, 2, 3, 255})
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func TestPackICNS(t *testing.T) {
	pngBytes := testPNG(t, 512)
	icns, err := packICNS(pngBytes)
	if err != nil {
		t.Fatal(err)
	}
	if string(icns[:4]) != "icns" {
		t.Fatalf("bad magic %q", icns[:4])
	}
	if got := binary.BigEndian.Uint32(icns[4:8]); int(got) != len(icns) {
		t.Fatalf("total length %d != %d", got, len(icns))
	}
	if string(icns[8:12]) != "ic09" { // 512 → ic09
		t.Fatalf("chunk type %q", icns[8:12])
	}
	if !bytes.Equal(icns[16:], pngBytes) {
		t.Fatal("PNG payload not verbatim")
	}
}

func TestPackICNSRejectsBadSizes(t *testing.T) {
	if _, err := packICNS(testPNG(t, 100)); err == nil {
		t.Fatal("100px should be rejected")
	}
	if _, err := packICNS([]byte("not a png")); err == nil {
		t.Fatal("non-PNG should be rejected")
	}
}

func TestEmbeddedIconPacks(t *testing.T) {
	// The committed asset must always be icns-packable — a bad swap-in
	// (wrong size, not PNG) fails here, not at a user's install.
	if _, err := packICNS(deliverIconPNG); err != nil {
		t.Fatalf("embedded icon does not pack: %v", err)
	}
}
