package commands

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"image"
	_ "image/png" // registered so icon dimensions can be decoded
	"strings"
)

// `byre deliver --install-app` materializes the DELIVER APP (GLOSSARY): host
// drag targets whose only job is invoking `byre deliver` on what you drop.
// Everything is a readable generated artifact (the Dockerfile.generated
// pattern — ADR 0021): byre writes text, the machine's own tooling makes it
// runnable (osacompile assembles the .app from Apple's signed applet stub;
// Automator and desktop launchers read their files as-is). Nothing prebuilt
// ever crosses a machine boundary, which is why no signing certificate or
// notarization is ever involved; install ad-hoc codesigns the bundle
// (`codesign --sign -`) as Apple Silicon belt-and-braces.
//
// This file holds the pure generators; install.go-side wiring writes them.

// dropletSource is the AppleScript for the "Byre Deliver" droplet. The byre
// path is baked at generation time (Finder launches carry a sparse PATH);
// well-known locations are fallbacks, and byre-not-found is reported via
// notification — a Dock launch has no terminal to print to.
func dropletSource(byrePath, box string) string {
	extra := ""
	if box != "" {
		extra = " --box " + shQuote(box)
	}
	return `-- Generated by byre. Do not edit; re-run: byre deliver --install-app
-- Byre Deliver: drop files here to deliver them into your running byre
-- box's /inbox; open it with nothing to deliver the CLIPBOARD instead.
-- byre prints the landed path, copies it to your clipboard, and reports
-- via notification. The binary below generated this app.

property byrePath : "` + asQuote(byrePath) + `"

on byreBinary()
	set candidates to {byrePath, "/opt/homebrew/bin/byre", "/usr/local/bin/byre", (POSIX path of (path to home folder)) & ".local/bin/byre"}
	repeat with c in candidates
		try
			do shell script "test -x " & quoted form of c
			return c as string
		end try
	end repeat
	display notification "byre not found — re-run 'byre deliver --install-app' after reinstalling byre" with title "Byre Deliver"
	error "byre not found"
end byreBinary

on open droppedItems
	set args to ""
	repeat with f in droppedItems
		set args to args & " " & quoted form of POSIX path of f
	end repeat
	runByre(args)
end open

on run
	runByre("")
end run

on runByre(args)
	try
		do shell script quoted form of byreBinary() & " deliver` + asQuote(extra) + `" & args & " </dev/null"
	on error errMsg
		-- byre notifies its own outcomes; this catches byre failing to RUN.
		display notification errMsg with title "Byre Deliver"
	end try
end runByre
`
}

// quickActionFiles is the Finder Quick Action ("Deliver to Byre"): an
// Automator .workflow bundle — two plists, read by the OS as-is.
func quickActionFiles(byrePath, box string) (infoPlist, documentWflow string) {
	extra := ""
	if box != "" {
		extra = " --box " + shQuote(box)
	}
	command := shQuote(byrePath) + " deliver" + extra + ` "$@" </dev/null`
	infoPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSServices</key>
	<array>
		<dict>
			<key>NSMenuItem</key>
			<dict>
				<key>default</key>
				<string>Deliver to Byre</string>
			</dict>
			<key>NSMessage</key>
			<string>runWorkflowAsService</string>
			<key>NSSendFileTypes</key>
			<array>
				<string>public.item</string>
			</array>
		</dict>
	</array>
</dict>
</plist>
`
	documentWflow = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AMApplicationBuild</key>
	<string>528</string>
	<key>AMApplicationVersion</key>
	<string>2.10</string>
	<key>AMDocumentVersion</key>
	<string>2</string>
	<key>actions</key>
	<array>
		<dict>
			<key>action</key>
			<dict>
				<key>AMActionVersion</key>
				<string>2.0.3</string>
				<key>AMParameterProperties</key>
				<dict>
					<key>COMMAND_STRING</key>
					<dict/>
					<key>CheckedForUserDefaultShell</key>
					<dict/>
					<key>inputMethod</key>
					<dict/>
					<key>shell</key>
					<dict/>
					<key>source</key>
					<dict/>
				</dict>
				<key>ActionBundlePath</key>
				<string>/System/Library/Automator/Run Shell Script.action</string>
				<key>ActionName</key>
				<string>Run Shell Script</string>
				<key>ActionParameters</key>
				<dict>
					<key>COMMAND_STRING</key>
					<string>` + xmlEscape(command) + `</string>
					<key>CheckedForUserDefaultShell</key>
					<true/>
					<key>inputMethod</key>
					<integer>1</integer>
					<key>shell</key>
					<string>/bin/bash</string>
					<key>source</key>
					<string></string>
				</dict>
				<key>BundleIdentifier</key>
				<string>com.apple.RunShellScript</string>
				<key>CFBundleVersion</key>
				<string>2.0.3</string>
				<key>CanShowSelectedItemsWhenRun</key>
				<false/>
				<key>CanShowWhenRun</key>
				<true/>
				<key>Class Name</key>
				<string>RunShellScriptAction</string>
				<key>InputUUID</key>
				<string>6E9F7A2C-0000-4000-8000-000000000001</string>
				<key>Keywords</key>
				<array>
					<string>Shell</string>
				</array>
				<key>OutputUUID</key>
				<string>6E9F7A2C-0000-4000-8000-000000000002</string>
				<key>UUID</key>
				<string>6E9F7A2C-0000-4000-8000-000000000003</string>
				<key>ignoresInput</key>
				<false/>
			</dict>
		</dict>
	</array>
	<key>connectors</key>
	<dict/>
	<key>workflowMetaData</key>
	<dict>
		<key>applicationBundleIDsByPath</key>
		<dict/>
		<key>applicationPaths</key>
		<array/>
		<key>inputTypeIdentifier</key>
		<string>com.apple.Automator.fileSystemObject</string>
		<key>outputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>presentationMode</key>
		<integer>15</integer>
		<key>processesInput</key>
		<false/>
		<key>serviceInputTypeIdentifier</key>
		<string>com.apple.Automator.fileSystemObject</string>
		<key>serviceOutputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>serviceProcessesInput</key>
		<false/>
		<key>systemImageName</key>
		<string>NSActionTemplate</string>
		<key>useAutomaticInputType</key>
		<false/>
		<key>workflowTypeIdentifier</key>
		<string>com.apple.Automator.servicesMenu</string>
	</dict>
</dict>
</plist>
`
	return infoPlist, documentWflow
}

// desktopEntry is the Linux launcher: Exec quoting per the Desktop Entry
// spec (path double-quoted with backslash-doubling; %F stays a field code).
func desktopEntry(byrePath, box string) string {
	extra := ""
	if box != "" {
		extra = " --box " + box // ids are byre-generated slugs; no spaces
	}
	return `# Generated by byre. Do not edit; re-run: byre deliver --install-app
[Desktop Entry]
Type=Application
Name=Byre Deliver
Comment=Deliver files to your running byre box's /inbox (run with no files to deliver the clipboard)
Exec=` + desktopExecQuote(byrePath) + ` deliver` + extra + ` %F
Icon=byre-deliver
Terminal=false
Categories=Utility;Development;
`
}

// packICNS wraps one PNG as a .icns (modern icns chunks carry PNG bytes
// directly — no Apple tooling involved). The source must be square at a
// size with an icns type: 128/256/512/1024; macOS scales one good high-res
// representation down gracefully.
func packICNS(pngBytes []byte) ([]byte, error) {
	cfg, format, err := image.DecodeConfig(bytes.NewReader(pngBytes))
	if err != nil || format != "png" {
		return nil, fmt.Errorf("icon must be a PNG: %v", err)
	}
	if cfg.Width != cfg.Height {
		return nil, fmt.Errorf("icon must be square (got %dx%d)", cfg.Width, cfg.Height)
	}
	types := map[int]string{128: "ic07", 256: "ic08", 512: "ic09", 1024: "ic10"}
	typ, ok := types[cfg.Width]
	if !ok {
		return nil, fmt.Errorf("icon must be 128, 256, 512, or 1024 px square (got %d)", cfg.Width)
	}
	var out bytes.Buffer
	chunkLen := uint32(8 + len(pngBytes))
	total := uint32(8) + chunkLen
	out.WriteString("icns")
	_ = binary.Write(&out, binary.BigEndian, total)
	out.WriteString(typ)
	_ = binary.Write(&out, binary.BigEndian, chunkLen)
	out.Write(pngBytes)
	return out.Bytes(), nil
}

// shQuote single-quotes for a POSIX shell.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// asQuote escapes for an AppleScript string literal.
func asQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	return strings.ReplaceAll(s, `"`, `\"`)
}

// xmlEscape escapes for plist string content.
func xmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;")
	return r.Replace(s)
}

// desktopExecQuote quotes one Exec argument per the Desktop Entry spec.
func desktopExecQuote(s string) string {
	if !strings.ContainsAny(s, " \t\"'\\><~|&;$*?#()`") {
		return s
	}
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
