package commands

import (
	"bytes"
	"fmt"
	"image"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/pjlsergeant/byre/internal/hostexec"
	"github.com/pjlsergeant/byre/internal/hostopen"
)

// looksByreGenerated reports whether content is one of byre's generated
// artifacts. Every generation, legacy included, begins a header comment
// with "Generated by byre." — AppleScript and desktop entries at byte 0,
// the Quick Action plist on the third line after the XML declaration
// and DOCTYPE. A line-anchored search would claim a foreign file that
// merely contains the phrase; the prologue check does not.
func looksByreGenerated(content []byte) bool {
	const mark = "Generated by byre."
	if bytes.HasPrefix(content, []byte("-- "+mark)) || bytes.HasPrefix(content, []byte("# "+mark)) {
		return true
	}
	rest := content
	for i := 0; i < 2; i++ {
		n := bytes.IndexByte(rest, '\n')
		if n < 0 {
			return false
		}
		rest = rest[n+1:]
	}
	return bytes.HasPrefix(rest, []byte("<!-- "+mark))
}

// installDeps are the host seams for --install-app, injectable for tests.
type installDeps struct {
	goos string
	home string
	exe  string // absolute path of the running byre binary
	run  func(name string, args ...string) error
}

// errNotByreGenerated refuses to overwrite an install-app artifact byre
// cannot recognize as its own: the user's file, the user's call.
func errNotByreGenerated(path string) error {
	return fmt.Errorf("%s exists and doesn't look byre-generated — remove it yourself and re-run", path)
}

// errWrongInstall refuses to regenerate an artifact that IS byre's but
// belongs to a different install: filename sanitization is many-to-one,
// so two labels can resolve to one path. Clobbering the first would
// silently break the coexistence promise; the collision is the user's
// to rename.
func errWrongInstall(path, otherLabel string) error {
	return fmt.Errorf("%s exists but belongs to the install labeled %q — pick a different --name", path, otherLabel)
}

func realInstallDeps() (installDeps, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return installDeps{}, fmt.Errorf("resolving home: %w", err)
	}
	exe, err := os.Executable()
	if err != nil {
		return installDeps{}, fmt.Errorf("resolving the byre binary path: %w", err)
	}
	if resolved, err := hostopen.PlainEvalSymlinks(exe, hostopen.HostUserOwned); err == nil {
		exe = resolved
	}
	return installDeps{
		goos: runtime.GOOS,
		home: home,
		exe:  exe,
		// installapp runs macOS build tools (osacompile, codesign, touch) over
		// artifacts under the user's home. It is user-invoked and carries no
		// project, so the root set is empty and every tool pins silently --
		// what the resolver buys here is the pin, one PATH read per tool.
		run: func(name string, args ...string) error {
			exe, lerr := hostexec.Look(name, hostexec.NewRoots())
			if lerr != nil {
				return fmt.Errorf("%s: %w", name, lerr)
			}
			out, err := exec.Command(exe, args...).CombinedOutput()
			if err != nil {
				return fmt.Errorf("%s: %s: %s", name, err, strings.TrimSpace(string(out)))
			}
			return nil
		},
	}, nil
}

// InstallApp materializes the deliver app (ADR 0021): the "Byre Deliver"
// drag-target app + "Deliver to Byre" Quick Action on macOS, the .desktop entry on
// Linux. A label (from --name, or the ssh:// target) names a coexisting
// install; unnamed local keeps the singleton artifact names. Idempotent
// regeneration of byre's OWN artifacts: an existing artifact is only
// replaced when it carries the generated marker — a same-named thing byre
// didn't write is refused, not clobbered.
func InstallApp(s Streams, o InstallAppOptions) error {
	deps, err := realInstallDeps()
	if err != nil {
		return err
	}
	return installApp(s, o, deps)
}

func installApp(s Streams, o InstallAppOptions, d installDeps) error {
	a, err := resolveInstall(d.exe, o)
	if err != nil {
		return err
	}
	switch d.goos {
	case "darwin":
		return installDarwin(s, a, d)
	default:
		return installLinux(s, a, d)
	}
}

func installDarwin(s Streams, a appInstall, d installDeps) error {
	appDir := filepath.Join(d.home, "Applications")
	appPath := filepath.Join(appDir, a.darwinAppName())
	if err := hostopen.PlainMkdirAll(appDir, 0o755, hostopen.HostUserOwned); err != nil {
		return err
	}
	source := deliverAppSource(a)

	// Regenerate only what byre wrote: the shipped source inside the bundle
	// is the marker. A same-named app WITHOUT it — or one whose state can't
	// even be established — is refused, never clobbered.
	marker := filepath.Join(appPath, "Contents", "Resources", "droplet.applescript")
	appExists := false
	switch _, err := hostopen.PlainStat(appPath, hostopen.HostUserOwned); {
	case err == nil:
		appExists = true
		// Judge the marker where it stands: ReadFile/WriteFile follow a
		// final-component symlink, so a link here would be read AND
		// written through, mutating its target — the same present-but-
		// unprovable rule as the icon gate.
		if fi, lerr := hostopen.PlainLstat(marker, hostopen.HostUserOwned); lerr != nil || !fi.Mode().IsRegular() {
			return errNotByreGenerated(appPath)
		}
		prev, rerr := hostopen.PlainReadFile(marker, hostopen.HostUserOwned)
		if rerr != nil || !looksByreGenerated(prev) {
			return errNotByreGenerated(appPath)
		}
		got, ok := installIDOf(prev)
		if !ok {
			return errNotByreGenerated(appPath)
		}
		if got != a.label {
			return errWrongInstall(appPath, got)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("checking %s: %w", appPath, err)
	}

	// Preflight the Quick Action destination BEFORE mutating the app: a
	// foreign workflow at its path refuses the whole install up front,
	// instead of surfacing after the app half was already committed and
	// announced (the failed command had half-happened,
	// making the error unreliable to interpret and the retry misleading).
	svcPath := filepath.Join(d.home, "Library", "Services", a.darwinWorkflowName())
	wflowPath := filepath.Join(svcPath, "Contents", "document.wflow")
	switch _, err := hostopen.PlainStat(svcPath, hostopen.HostUserOwned); {
	case err == nil:
		// Same no-follow rule as the app marker above.
		if fi, lerr := hostopen.PlainLstat(wflowPath, hostopen.HostUserOwned); lerr != nil || !fi.Mode().IsRegular() {
			return errNotByreGenerated(svcPath)
		}
		prev, rerr := hostopen.PlainReadFile(wflowPath, hostopen.HostUserOwned)
		if rerr != nil || !looksByreGenerated(prev) {
			return errNotByreGenerated(svcPath)
		}
		got, ok := installIDOf(prev)
		if !ok {
			return errNotByreGenerated(svcPath)
		}
		if got != a.label {
			return errWrongInstall(svcPath, got)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("checking %s: %w", svcPath, err)
	}

	srcDir, err := hostopen.PlainMkdirTemp("", "byre-deliver-app-", hostopen.ProcessTemp)
	if err != nil {
		return err
	}
	defer hostopen.PlainRemoveAll(srcDir, hostopen.ByreCreated)
	srcPath := filepath.Join(srcDir, "droplet.applescript")
	if err := hostopen.PlainWriteFile(srcPath, []byte(source), 0o644, hostopen.ByreCreated); err != nil {
		return err
	}
	// Assemble into a STAGED bundle first: a broken osacompile, bad disk, or
	// malformed source must never destroy the working app already installed.
	// Same parent dir, so the final swap is one rename. The staging
	// directory is a private mktemp name so a user's file at a guessed
	// sibling path is never the collateral of --name.
	stageDir, err := hostopen.PlainMkdirTemp(appDir, ".byre-deliver-stage-", hostopen.HostUserOwned)
	if err != nil {
		return err
	}
	staged := filepath.Join(stageDir, "staged.app")
	backup := filepath.Join(stageDir, "previous.app")
	// osacompile assembles the bundle from Apple's signed applet stub — the
	// whole "compile": no toolchain, no network, milliseconds (ADR 0021).
	if err := d.run("osacompile", "-o", staged, srcPath); err != nil {
		_ = hostopen.PlainRemoveAll(stageDir, hostopen.HostUserOwned)
		return fmt.Errorf("assembling the app (osacompile): %w", err)
	}
	// Ship the readable source in the bundle — the artifact stays inspectable.
	if err := hostopen.PlainWriteFile(filepath.Join(staged, "Contents", "Resources", "droplet.applescript"), []byte(source), 0o644, hostopen.HostUserOwned); err != nil {
		_ = hostopen.PlainRemoveAll(stageDir, hostopen.HostUserOwned)
		return err
	}
	// Icon: overwrite the stub's droplet/applet icns with ours.
	if icns, err := packICNS(a.iconPNG()); err == nil {
		for _, name := range []string{"droplet.icns", "applet.icns"} {
			_ = hostopen.PlainWriteFile(filepath.Join(staged, "Contents", "Resources", name), icns, 0o644, hostopen.HostUserOwned)
		}
	} else {
		fmt.Fprintf(s.Err, "byre: warning: icon skipped (%v)\n", err)
	}
	// Overwriting the resources above invalidated the signature the applet stub
	// arrived with (osacompile assembles from Apple's signed stub). Re-sign ad-hoc
	// -- no certificate involved -- so macOS is not asked to launch a bundle whose
	// signature is present but broken, which is worse off than an unsigned one.
	if err := d.run("codesign", "--force", "--deep", "--sign", "-", staged); err != nil {
		fmt.Fprintf(s.Err, "byre: warning: ad-hoc codesign failed (%v) — the app usually still runs; if macOS refuses it, this is why\n", err)
	}
	// The swap, with the old app held as a restorable backup until the new
	// one is actually in place — no window where a rename failure leaves
	// NEITHER bundle installed. Every exit removes stageDir except the
	// catastrophic path (install rename failed AND restore rename failed),
	// which names the backup inside stageDir and leaves it alive.
	if appExists {
		if err := hostopen.PlainRename(appPath, backup, hostopen.HostUserOwned); err != nil {
			_ = hostopen.PlainRemoveAll(stageDir, hostopen.HostUserOwned)
			return fmt.Errorf("setting the old app aside: %w", err)
		}
		if err := hostopen.PlainRename(staged, appPath, hostopen.HostUserOwned); err != nil {
			_ = hostopen.PlainRemoveAll(staged, hostopen.HostUserOwned)
			if rerr := hostopen.PlainRename(backup, appPath, hostopen.HostUserOwned); rerr != nil {
				// The one truly bad outcome: say exactly where the working
				// app still lives instead of claiming a restore that failed.
				return fmt.Errorf("installing the assembled app failed (%v) AND restoring the old one failed (%v) — your previous app is intact at %s; rename it back by hand", err, rerr, backup)
			}
			_ = hostopen.PlainRemoveAll(stageDir, hostopen.HostUserOwned)
			return fmt.Errorf("installing the assembled app (old app restored): %w", err)
		}
	} else if err := hostopen.PlainRename(staged, appPath, hostopen.HostUserOwned); err != nil {
		_ = hostopen.PlainRemoveAll(stageDir, hostopen.HostUserOwned)
		return fmt.Errorf("installing the assembled app: %w", err)
	}
	if err := hostopen.PlainRemoveAll(stageDir, hostopen.HostUserOwned); err != nil {
		fmt.Fprintf(s.Err, "byre: warning: could not remove the staging directory at %s (%v) — delete it yourself\n", stageDir, err)
	}
	_ = d.run("touch", appPath) // nudge Finder's icon cache
	fmt.Fprintf(s.Out, "%s\n", appPath)
	fmt.Fprintf(s.Err, "byre: installed the deliver app — drag it to the Dock, drop files on it, or open it to deliver the clipboard\n")

	// The Finder Quick Action (right-click → Deliver to Byre). Ownership was
	// preflighted above, before the app was touched; regeneration is gated
	// on the explicit generated marker there.
	info, wflow := quickActionFiles(a)
	if err := hostopen.PlainMkdirAll(filepath.Join(svcPath, "Contents"), 0o755, hostopen.HostUserOwned); err != nil {
		return err
	}
	if err := hostopen.PlainWriteFile(filepath.Join(svcPath, "Contents", "Info.plist"), []byte(info), 0o644, hostopen.HostUserOwned); err != nil {
		return err
	}
	if err := hostopen.PlainWriteFile(wflowPath, []byte(wflow), 0o644, hostopen.HostUserOwned); err != nil {
		return err
	}
	fmt.Fprintf(s.Out, "%s\n", svcPath)
	fmt.Fprintf(s.Err, "byre: installed the Quick Action — right-click files in Finder → Quick Actions → %s\n", a.menuItem())
	fmt.Fprintf(s.Err, "byre: first use asks macOS permission prompts once (Automation/notifications) — that's expected\n")
	fmt.Fprintf(s.Err, "byre: to uninstall: delete the two paths above\n")
	fmt.Fprintf(s.Err, "byre: to update (byre moved, new --box): re-run '%s'\n", a.rerun())
	return nil
}

func installLinux(s Streams, a appInstall, d installDeps) error {
	appsDir := filepath.Join(d.home, ".local", "share", "applications")
	entryPath := filepath.Join(appsDir, a.linuxDesktopName())
	// Judge the entry where it stands (no-follow): a symlink here would
	// be read and then written through, mutating its target.
	if fi, lerr := hostopen.PlainLstat(entryPath, hostopen.HostUserOwned); lerr == nil && !fi.Mode().IsRegular() {
		return errNotByreGenerated(entryPath)
	}
	switch prev, err := hostopen.PlainReadFile(entryPath, hostopen.HostUserOwned); {
	case err == nil:
		if !looksByreGenerated(prev) {
			return errNotByreGenerated(entryPath)
		}
		got, ok := installIDOf(prev)
		if !ok {
			return errNotByreGenerated(entryPath)
		}
		if got != a.label {
			return errWrongInstall(entryPath, got)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("checking %s: %w", entryPath, err)
	}
	if err := hostopen.PlainMkdirAll(appsDir, 0o755, hostopen.HostUserOwned); err != nil {
		return err
	}
	if err := hostopen.PlainWriteFile(entryPath, []byte(desktopEntry(a)), 0o644, hostopen.HostUserOwned); err != nil {
		return err
	}
	fmt.Fprintf(s.Out, "%s\n", entryPath)

	// The icon lands in the hicolor theme at its actual size. A PNG can't
	// carry the text marker, so ownership is judged by content: byre only
	// ever writes the embedded assets, so anything else at the path is
	// someone's file — skipped with a note, never clobbered (the icon is
	// cosmetic; the install still lands).
	png := a.iconPNG()
	if cfg, _, err := image.DecodeConfig(bytes.NewReader(png)); err == nil {
		iconDir := filepath.Join(d.home, ".local", "share", "icons", "hicolor",
			fmt.Sprintf("%dx%d", cfg.Width, cfg.Height), "apps")
		if err := hostopen.PlainMkdirAll(iconDir, 0o755, hostopen.HostUserOwned); err != nil {
			fmt.Fprintf(s.Err, "byre: warning: icon not installed — %s: %v\n", iconDir, err)
		} else {
			iconPath := filepath.Join(iconDir, a.iconName()+".png")
			// Existence is established by Lstat, not by whether a read
			// succeeded: an unreadable file, a directory, or a symlink is
			// PRESENT but of unprovable ownership — skipped, never written
			// (a write would truncate a 0200 file the read couldn't see,
			// or follow a symlink somewhere else entirely).
			write := false
			if fi, lerr := hostopen.PlainLstat(iconPath, hostopen.HostUserOwned); lerr == nil {
				existing, rerr := hostopen.PlainReadFile(iconPath, hostopen.HostUserOwned)
				if fi.Mode().IsRegular() && rerr == nil &&
					(bytes.Equal(existing, deliverIconPNG) || bytes.Equal(existing, deliverIconSSHPNG)) {
					write = true
				} else {
					fmt.Fprintf(s.Err, "byre: warning: icon skipped — %s exists and doesn't look byre-written; remove it yourself and re-run\n", iconPath)
				}
			} else if os.IsNotExist(lerr) {
				write = true
			} else {
				fmt.Fprintf(s.Err, "byre: warning: icon skipped — cannot check %s (%v)\n", iconPath, lerr)
			}
			if write {
				if err := hostopen.PlainWriteFile(iconPath, png, 0o644, hostopen.HostUserOwned); err != nil {
					fmt.Fprintf(s.Err, "byre: warning: icon not installed — %s: %v\n", iconPath, err)
				} else {
					fmt.Fprintf(s.Out, "%s\n", iconPath)
				}
			}
		}
	}
	fmt.Fprintf(s.Err, "byre: installed the deliver launcher — drag files onto it in your app grid/dock\n")
	fmt.Fprintf(s.Err, "byre: NOTE — the Linux graphical path (dropping files on the launcher, the\n")
	fmt.Fprintf(s.Err, "byre:   picker dialog, notifications) is EXPERIMENTAL and unverified across\n")
	fmt.Fprintf(s.Err, "byre:   desktop environments; some don't support launcher drops at all. The\n")
	fmt.Fprintf(s.Err, "byre:   'byre deliver <file>' terminal flow is the supported path. Reports welcome.\n")
	fmt.Fprintf(s.Err, "byre: to uninstall: delete the paths above\n")
	fmt.Fprintf(s.Err, "byre: to update (byre moved, new --box): re-run '%s'\n", a.rerun())
	return nil
}
