package commands

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/pjlsergeant/byre/internal/config"
	"github.com/pjlsergeant/byre/internal/project"
)

// Rehome implements `byre rehome <old-id>`: migrate a previous project's named
// volumes AND its stored config onto the identity of the current directory
// (after a move/rename, which changes the path-derived id). Docker has no
// volume rename, so each volume is copy-then-remove. Refuses while a session
// is live for either id; pre-checks for destination conflicts; removes the
// old volumes only after every copy succeeds. On success the old id's image
// and store dir are retired too — a completed rehome must not leave the old
// id in the candidate list forever, or strand an adopted store-only config.
func Rehome(s Streams, projectDir, oldID string) error {
	// The id is user-typed and becomes a store path component and a volume-name
	// prefix; a malformed one can't have been generated by byre, so refuse it
	// up front (find the real one with `byre status` in the old location, or
	// `ls ~/.byre/projects`).
	if !project.ValidID(oldID) {
		return fmt.Errorf("%q is not a byre project id (expected slug-hash, e.g. byre-dev-0877d7)", oldID)
	}
	paths, err := project.Resolve(projectDir)
	if err != nil {
		return err
	}
	// A worktree has no identity of its own to rehome — it inherits the main
	// worktree's. Its path only feeds the container name/label, derived fresh each
	// run, so a moved worktree self-heals. Point at the main tree instead of
	// migrating the shared (inherited) volumes onto a worktree-derived id.
	if paths.IsWorktree {
		return fmt.Errorf("this is a worktree of %s; run rehome from the main worktree if the repo moved (a worktree inherits its identity and needs no rehome)", paths.Canonical)
	}
	if err := paths.Bootstrap(); err != nil {
		return err
	}
	engines, err := lifecycleEngines()
	if err != nil {
		return err
	}
	return rehome(s, paths, oldID, engines, os.Getuid(), os.Getgid())
}

func rehome(s Streams, paths project.Paths, oldID string, engines []engineRunner, uid, gid int) error {
	newID := paths.ID
	if oldID == newID {
		return fmt.Errorf("already homed here (id %s)", newID)
	}

	// All checks and mutations run under BOTH the old and new projects' setup
	// locks (so a concurrent develop/seed on either id can't race the
	// migration), with the live-session checks re-evaluated inside.
	oldDir := filepath.Join(paths.Home, "projects", oldID)
	oldLock := filepath.Join(oldDir, "lock")
	if err := os.MkdirAll(filepath.Dir(oldLock), 0o755); err != nil {
		return err
	}
	// Set under the locks, acted on after: the old store dir holds the lock
	// file itself, so it can only be removed once the lock is released
	// (forget's store removal has the same shape).
	removeOldStore := false
	if err := withTwoSetupLocks(s.Err, paths.LockFile, oldLock, func() error {
		multi := len(engines) > 1
		// Both ids' sessions block a migration, on every installed engine; a
		// pre-start marker on either id (a develop between create and start) is
		// dissolved so that develop fails loudly rather than launching
		// mid-migration.
		for _, r := range engines {
			for _, id := range []string{oldID, newID} {
				if err := clearSessionMarkers(s.Err, r, id); err != nil {
					return err
				}
			}
		}

		// Volumes are engine-local (there is no cross-engine copy vehicle), so
		// each engine's old volumes migrate within that engine — but planned,
		// copied, and retired as ONE transaction across engines: every
		// engine's plan is conflict-checked before any copy, every copy lands
		// before any source is removed, and a copy failure rolls back every
		// destination created (on any engine) with the sources intact. Without
		// that, a podman-side conflict would surface only after docker's
		// sources were already gone.
		var plans []enginePlan
		for _, r := range engines {
			pl, err := planRehomeVolumes(paths, oldID, r, uid, gid, multi)
			if err != nil {
				return err
			}
			if len(pl.pairs) > 0 {
				plans = append(plans, pl)
			}
		}
		for i := range plans {
			if err := copyRehomeVolumes(s, &plans[i], uid, gid, multi); err != nil {
				for _, done := range plans[:i+1] {
					rollback(done.r, done.created)
				}
				return err
			}
		}
		migratedAny := len(plans) > 0

		// The stored config follows the identity: a store-only (adopted or
		// hand-written) byre.config would otherwise be silently orphaned and
		// the new id re-onboarded from scratch. Runs BEFORE any source is
		// retired: everything that can FAIL must fail while the old volumes
		// (and the rollback below) still make a clean re-run possible — from
		// the retirement steps on, problems are warned, never fatal.
		storeFound, storeSafe, serr := migrateStore(s, paths, oldDir)
		if serr != nil {
			for _, pl := range plans {
				rollback(pl.r, pl.created)
			}
			return serr
		}
		if !migratedAny && !storeFound {
			fmt.Fprintf(s.Err, "byre: nothing found for old id %s (no volumes, no stored config); nothing to migrate\n", oldID)
			return nil
		}

		// Every copy landed and the store followed — retire the sources.
		for _, pl := range plans {
			for _, p := range pl.pairs {
				if err := pl.r.VolumeRemove(p.src); err != nil {
					fmt.Fprintf(s.Err, "byre: warning: copied but could not remove old volume %s%s: %v\n", p.src, engineSuffix(multi, pl.r), err)
				}
			}
		}

		// The old id's image is permanently orphaned by the move (the new id
		// builds its own tag); retire it. A failure is warned, not fatal — the
		// image is engine-side garbage, not migration state.
		for _, r := range engines {
			for _, img := range []string{imageTag(oldID, uid, gid), "byre-" + oldID} {
				has, ierr := r.ImageExists(img)
				if ierr != nil {
					fmt.Fprintf(s.Err, "byre: warning: could not check old image %s%s: %v\n", img, engineSuffix(multi, r), ierr)
					continue
				}
				if has {
					if rerr := r.ImageRemove(img); rerr != nil {
						fmt.Fprintf(s.Err, "byre: warning: could not remove old image %s%s: %v\n", img, engineSuffix(multi, r), rerr)
					}
				}
			}
		}

		// The old store's contents die INSIDE the critical section (a develop
		// on the old id queued on its lock must never interleave with the
		// deletion); only the dir + lock file survive to the post-release
		// removal below. Warn-only from here: sources are already retired, so
		// failing now would leave an error atop a committed migration — the
		// leftover store is a candidate-list wart, not migration state.
		if storeSafe {
			if cerr := clearStoreContents(oldDir); cerr != nil {
				fmt.Fprintf(s.Err, "byre: warning: could not remove the old store contents: %v — the old id stays a rehome candidate until %s is deleted by hand.\n", cerr, oldDir)
			} else {
				removeOldStore = true
			}
		}
		fmt.Fprintf(s.Err, "byre: rehomed %s -> %s. Run `byre develop` to rebuild the image.\n", oldID, newID)
		return nil
	}); err != nil {
		return err
	}

	if removeOldStore {
		if rerr := removeEmptiedStore(oldDir); rerr != nil {
			fmt.Fprintf(s.Err, "byre: warning: %v — the old id will keep appearing as a rehome candidate until deleted.\n", rerr)
		}
	}
	return nil
}

// migrateStore copies the old store's config and adoption records
// (byre.config, adopted, declined) into the new id's store when the new store
// doesn't already hold them. found reports whether the old store held any
// identity worth migrating (those files, or a path record — the thing that
// makes it a rehome-candidate zombie); safe reports whether the old store may
// be deleted afterwards — false when a conflicting file had to be left
// behind (deleting it then would destroy the only copy).
func migrateStore(s Streams, paths project.Paths, oldDir string) (found, safe bool, err error) {
	safe = true
	if _, e := os.Stat(filepath.Join(oldDir, "path")); e == nil {
		found = true
	}
	for _, name := range []string{config.ProjectConfigName, appliedRecord} {
		src := filepath.Join(oldDir, name)
		content, rerr := os.ReadFile(src)
		if rerr != nil {
			if os.IsNotExist(rerr) {
				continue
			}
			return found, false, fmt.Errorf("reading %s: %w", src, rerr)
		}
		found = true
		dst := filepath.Join(paths.Dir, name)
		existing, derr := os.ReadFile(dst)
		switch {
		case derr == nil && bytes.Equal(existing, content):
			// Already identical at the new id — nothing to do.
		case derr == nil:
			// The new id already has its own (e.g. it was onboarded before the
			// user remembered to rehome). Never clobber it, and never delete
			// the only copy of the old one.
			fmt.Fprintf(s.Err, "byre: NOT copied: %s differs from the new id's existing one; the old store stays at %s — reconcile by hand.\n", name, oldDir)
			safe = false
		case os.IsNotExist(derr):
			if werr := config.AtomicWrite(dst, string(content)); werr != nil {
				return found, false, fmt.Errorf("copying %s to the new id: %w", name, werr)
			}
			fmt.Fprintf(s.Err, "byre: copied stored %s to the new id\n", name)
		default:
			return found, false, fmt.Errorf("checking %s: %w", dst, derr)
		}
	}
	return found, safe, nil
}

// enginePlan is one engine's slice of the rehome transaction: the volume
// copies to run (already conflict-checked), the image to run them with, and
// the destinations created so far — the cross-engine rollback list.
type enginePlan struct {
	r       engineRunner
	image   string
	pairs   []volPair
	created []string
}

type volPair struct{ src, dst string }

// planRehomeVolumes validates one engine's migration without mutating
// anything: lists the old id's volumes, picks the copy image, and
// conflict-checks every destination. An empty pairs list means this engine
// holds nothing to move.
func planRehomeVolumes(paths project.Paths, oldID string, r engineRunner, uid, gid int, multi bool) (enginePlan, error) {
	newID := paths.ID
	oldPrefix := "byre-" + oldID + "-"
	pl := enginePlan{r: r}
	oldVols, err := projectVolumes(r, paths.Home, oldID)
	if err != nil {
		return pl, fmt.Errorf("listing volumes (%s): %w", r.Engine(), err)
	}
	if len(oldVols) == 0 {
		return pl, nil
	}
	// An image is needed to run the copies; prefer the old one, else the new one.
	pl.image, err = pickCopyImage(r, oldID, newID, uid, gid)
	if err != nil {
		return pl, err
	}
	for _, src := range oldVols {
		dst := "byre-" + newID + "-" + strings.TrimPrefix(src, oldPrefix)
		exists, err := r.VolumeExists(dst)
		if err != nil {
			return pl, err
		}
		if exists {
			return pl, fmt.Errorf("destination volume %s already exists%s; resolve the conflict (e.g. byre reset) before rehome", dst, engineSuffix(multi, r))
		}
		pl.pairs = append(pl.pairs, volPair{src, dst})
	}
	return pl, nil
}

// copyRehomeVolumes executes one engine's copies, recording every created
// destination into the plan so the caller can roll back ACROSS engines on
// failure. It never removes a source — retirement happens only after every
// engine's copies landed.
func copyRehomeVolumes(s Streams, pl *enginePlan, uid, gid int, multi bool) error {
	for _, p := range pl.pairs {
		if err := pl.r.VolumeCreate(p.dst); err != nil {
			return fmt.Errorf("creating %s: %w", p.dst, err)
		}
		pl.created = append(pl.created, p.dst)
		if err := pl.r.MigrateVolume(p.src, p.dst, pl.image, uid, gid); err != nil {
			return fmt.Errorf("copying %s -> %s: %w", p.src, p.dst, err)
		}
		fmt.Fprintf(s.Err, "byre: migrated %s -> %s%s\n", p.src, p.dst, engineSuffix(multi, pl.r))
	}
	return nil
}

func pickCopyImage(r imageRunner, oldID, newID string, uid, gid int) (string, error) {
	// Try each id's current (UID-qualified) tag, then its legacy unqualified
	// `byre-<id>` tag — a project built before the build-time-UID milestone still
	// has only that. The copy one-shot (MigrateVolume) bypasses the entrypoint,
	// runs as root, and chowns explicitly, so the image's own baked uid is
	// irrelevant: any byre image for these ids works as the copy vehicle.
	for _, id := range []string{oldID, newID} {
		for _, img := range []string{imageTag(id, uid, gid), "byre-" + id} {
			if ok, err := r.ImageExists(img); err != nil {
				return "", err
			} else if ok {
				return img, nil
			}
		}
	}
	return "", fmt.Errorf("no byre image exists to run the volume copy; run `byre develop` first")
}

func rollback(r volumeRunner, created []string) {
	for _, v := range created {
		_ = r.VolumeRemove(v)
	}
}

// rehomeCandidate is one stored project whose recorded path no longer exists —
// exactly what a move/rename leaves behind.
type rehomeCandidate struct {
	ID       string
	WasPath  string
	LastUsed time.Time
}

// RehomeCandidates implements bare `byre rehome`, a valid query of its own:
// list the stored projects whose recorded path no longer exists — the ids a
// move/rename orphans — most recently used first, so the id the user needs is
// usually the top line. Ids whose recorded path still exists are not offered:
// the id is derived from the path, so an existing path IS that project's
// current home.
func RehomeCandidates(s Streams, projectDir string) error {
	paths, err := project.Resolve(projectDir)
	if err != nil {
		return err
	}
	cands, total, err := rehomeCandidates(paths)
	if err != nil {
		return err
	}
	if total == 0 {
		// total counts OTHER stored projects with a readable path record — the
		// store may well contain this project itself, so don't claim "empty".
		fmt.Fprintln(s.Out, "byre: no other stored projects — nothing to rehome from.")
		return nil
	}
	if len(cands) == 0 {
		// Not "every path still exists": an unverifiable (e.g. EACCES) path was
		// skipped, not confirmed present.
		fmt.Fprintf(s.Out, "byre: none of the %d other stored project(s) look moved.\n", total)
		return nil
	}
	fmt.Fprintln(s.Out, "byre: stored projects whose recorded path no longer exists (likely rehome candidates), most recent first:")
	w := 0
	for _, c := range cands {
		if len(c.ID) > w {
			w = len(c.ID)
		}
	}
	for _, c := range cands {
		fmt.Fprintf(s.Out, "  %-*s   last used %s   was %s\n", w, c.ID, c.LastUsed.Format("2006-01-02"), c.WasPath)
	}
	return nil
}

// rehomeCandidates scans the project store for moved projects. total is the
// number of stored projects considered (excluding this directory's own id), so
// the caller can distinguish "no store" from "nothing moved".
func rehomeCandidates(paths project.Paths) (cands []rehomeCandidate, total int, err error) {
	entries, err := os.ReadDir(filepath.Join(paths.Home, "projects"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, 0, nil
		}
		return nil, 0, err
	}
	for _, e := range entries {
		id := e.Name()
		if !e.IsDir() || !project.ValidID(id) || id == paths.ID {
			continue
		}
		dir := filepath.Join(paths.Home, "projects", id)
		rec, rerr := os.ReadFile(filepath.Join(dir, "path"))
		if rerr != nil {
			// No readable path record — half-bootstrapped or foreign; it can't
			// be shown as "moved from" anywhere, so don't offer it.
			continue
		}
		total++
		was := strings.TrimSuffix(string(rec), "\n")
		_, serr := os.Stat(was)
		if serr == nil {
			continue // path still exists: that project still lives there
		}
		if !errors.Is(serr, fs.ErrNotExist) {
			// EACCES and friends: the path can't be VERIFIED missing, so don't
			// claim it moved.
			continue
		}
		cands = append(cands, rehomeCandidate{ID: id, WasPath: was, LastUsed: lastUsed(dir)})
	}
	sort.Slice(cands, func(i, j int) bool { return cands[i].LastUsed.After(cands[j].LastUsed) })
	return cands, total, nil
}

// lastUsed approximates a stored project's last activity: the generated
// Dockerfile is re-staged on every develop, so its mtime is the best cheap
// signal; the path record's mtime (creation) is the floor.
func lastUsed(projectDir string) time.Time {
	var t time.Time
	for _, f := range []string{
		filepath.Join(projectDir, "context", "Dockerfile.generated"),
		filepath.Join(projectDir, "path"),
	} {
		if fi, err := os.Stat(f); err == nil && fi.ModTime().After(t) {
			t = fi.ModTime()
		}
	}
	return t
}
