package commands

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/pjlsergeant/byre/internal/project"
)

// Rehome implements `byre rehome <old-id>`: migrate a previous project's named
// volumes onto the identity of the current directory (after a move/rename, which
// changes the path-derived id). Docker has no volume rename, so each volume is
// copy-then-remove. Refuses while a session is live for either id; pre-checks
// for destination conflicts; removes the old volumes only after every copy
// succeeds.
func Rehome(s Streams, projectDir, oldID string) error {
	// The id is user-typed and becomes a store path component and a volume-name
	// prefix; a malformed one can't have been generated by byre, so refuse it
	// up front (find the real one with `byre status` in the old location, or
	// `ls ~/.byre/projects`).
	if !project.ValidID(oldID) {
		return fmt.Errorf("%q is not a byre project id (expected slug-hash, e.g. byre-dev-0877d7)", oldID)
	}
	paths, err := project.Resolve(projectDir)
	if err != nil {
		return err
	}
	// A worktree has no identity of its own to rehome — it inherits the main
	// worktree's. Its path only feeds the container name/label, derived fresh each
	// run, so a moved worktree self-heals. Point at the main tree instead of
	// migrating the shared (inherited) volumes onto a worktree-derived id.
	if paths.IsWorktree {
		return fmt.Errorf("this is a worktree of %s; run rehome from the main worktree if the repo moved (a worktree inherits its identity and needs no rehome)", paths.Canonical)
	}
	if err := paths.Bootstrap(); err != nil {
		return err
	}
	r, err := resolveEngine(s.Err, projectDir)
	if err != nil {
		return err
	}
	return rehome(s, paths, oldID, r, os.Getuid(), os.Getgid())
}

func rehome(s Streams, paths project.Paths, oldID string, r engineRunner, uid, gid int) error {
	newID := paths.ID
	if oldID == newID {
		return fmt.Errorf("already homed here (id %s)", newID)
	}

	// All checks and mutations run under BOTH the old and new projects' setup
	// locks (so a concurrent develop/seed on either id can't race the
	// migration), with the live-session checks re-evaluated inside.
	oldLock := filepath.Join(paths.Home, "projects", oldID, "lock")
	if err := os.MkdirAll(filepath.Dir(oldLock), 0o755); err != nil {
		return err
	}
	return withTwoSetupLocks(s.Err, paths.LockFile, oldLock, func() error {
		// Both ids' sessions block a migration; a pre-start marker on either id
		// (a develop between create and start) is dissolved so that develop
		// fails loudly rather than launching mid-migration.
		for _, id := range []string{oldID, newID} {
			if err := clearSessionMarkers(s.Err, r, id); err != nil {
				return err
			}
		}

		oldPrefix := "byre-" + oldID + "-"
		oldVols, err := projectVolumes(r, paths.Home, oldID)
		if err != nil {
			return err
		}
		if len(oldVols) == 0 {
			fmt.Fprintf(s.Err, "byre: no volumes found for old id %s; nothing to migrate\n", oldID)
			return nil
		}

		// An image is needed to run the copy; prefer the old one, else the new one.
		image, err := pickCopyImage(r, oldID, newID, uid, gid)
		if err != nil {
			return err
		}

		// Pre-check all destinations for conflicts before mutating anything.
		type pair struct{ src, dst string }
		var plan []pair
		for _, src := range oldVols {
			dst := "byre-" + newID + "-" + strings.TrimPrefix(src, oldPrefix)
			exists, err := r.VolumeExists(dst)
			if err != nil {
				return err
			}
			if exists {
				return fmt.Errorf("destination volume %s already exists; resolve the conflict (e.g. byre reset) before rehome", dst)
			}
			plan = append(plan, pair{src, dst})
		}

		// Copy each old volume into a fresh destination. On any failure, roll back
		// the destinations created so far and leave the originals intact.
		var created []string
		for _, p := range plan {
			if err := r.VolumeCreate(p.dst); err != nil {
				rollback(r, created)
				return fmt.Errorf("creating %s: %w", p.dst, err)
			}
			created = append(created, p.dst)
			if err := r.MigrateVolume(p.src, p.dst, image, uid, gid); err != nil {
				rollback(r, created)
				return fmt.Errorf("copying %s -> %s: %w", p.src, p.dst, err)
			}
			fmt.Fprintf(s.Err, "byre: migrated %s -> %s\n", p.src, p.dst)
		}

		// All copies succeeded — now remove the originals.
		for _, p := range plan {
			if err := r.VolumeRemove(p.src); err != nil {
				fmt.Fprintf(s.Err, "byre: warning: copied but could not remove old volume %s: %v\n", p.src, err)
			}
		}
		fmt.Fprintf(s.Err, "byre: rehomed %s -> %s. Run `byre develop` to rebuild the image.\n", oldID, newID)
		return nil
	})
}

func pickCopyImage(r imageRunner, oldID, newID string, uid, gid int) (string, error) {
	// Try each id's current (UID-qualified) tag, then its legacy unqualified
	// `byre-<id>` tag — a project built before the build-time-UID milestone still
	// has only that. The copy one-shot (MigrateVolume) bypasses the entrypoint,
	// runs as root, and chowns explicitly, so the image's own baked uid is
	// irrelevant: any byre image for these ids works as the copy vehicle.
	for _, id := range []string{oldID, newID} {
		for _, img := range []string{imageTag(id, uid, gid), "byre-" + id} {
			if ok, err := r.ImageExists(img); err != nil {
				return "", err
			} else if ok {
				return img, nil
			}
		}
	}
	return "", fmt.Errorf("no byre image exists to run the volume copy; run `byre develop` first")
}

func rollback(r volumeRunner, created []string) {
	for _, v := range created {
		_ = r.VolumeRemove(v)
	}
}

// rehomeCandidate is one stored project whose recorded path no longer exists —
// exactly what a move/rename leaves behind.
type rehomeCandidate struct {
	ID       string
	WasPath  string
	LastUsed time.Time
}

// RehomeCandidates implements bare `byre rehome`, a valid query of its own:
// list the stored projects whose recorded path no longer exists — the ids a
// move/rename orphans — most recently used first, so the id the user needs is
// usually the top line. Ids whose recorded path still exists are not offered:
// the id is derived from the path, so an existing path IS that project's
// current home.
func RehomeCandidates(s Streams, projectDir string) error {
	paths, err := project.Resolve(projectDir)
	if err != nil {
		return err
	}
	cands, total, err := rehomeCandidates(paths)
	if err != nil {
		return err
	}
	if total == 0 {
		// total counts OTHER stored projects with a readable path record — the
		// store may well contain this project itself, so don't claim "empty".
		fmt.Fprintln(s.Out, "byre: no other stored projects — nothing to rehome from.")
		return nil
	}
	if len(cands) == 0 {
		// Not "every path still exists": an unverifiable (e.g. EACCES) path was
		// skipped, not confirmed present.
		fmt.Fprintf(s.Out, "byre: none of the %d other stored project(s) look moved.\n", total)
		return nil
	}
	fmt.Fprintln(s.Out, "byre: stored projects whose recorded path no longer exists (likely rehome candidates), most recent first:")
	w := 0
	for _, c := range cands {
		if len(c.ID) > w {
			w = len(c.ID)
		}
	}
	for _, c := range cands {
		fmt.Fprintf(s.Out, "  %-*s   last used %s   was %s\n", w, c.ID, c.LastUsed.Format("2006-01-02"), c.WasPath)
	}
	return nil
}

// rehomeCandidates scans the project store for moved projects. total is the
// number of stored projects considered (excluding this directory's own id), so
// the caller can distinguish "no store" from "nothing moved".
func rehomeCandidates(paths project.Paths) (cands []rehomeCandidate, total int, err error) {
	entries, err := os.ReadDir(filepath.Join(paths.Home, "projects"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, 0, nil
		}
		return nil, 0, err
	}
	for _, e := range entries {
		id := e.Name()
		if !e.IsDir() || !project.ValidID(id) || id == paths.ID {
			continue
		}
		dir := filepath.Join(paths.Home, "projects", id)
		rec, rerr := os.ReadFile(filepath.Join(dir, "path"))
		if rerr != nil {
			// No readable path record — half-bootstrapped or foreign; it can't
			// be shown as "moved from" anywhere, so don't offer it.
			continue
		}
		total++
		was := strings.TrimSuffix(string(rec), "\n")
		_, serr := os.Stat(was)
		if serr == nil {
			continue // path still exists: that project still lives there
		}
		if !errors.Is(serr, fs.ErrNotExist) {
			// EACCES and friends: the path can't be VERIFIED missing, so don't
			// claim it moved.
			continue
		}
		cands = append(cands, rehomeCandidate{ID: id, WasPath: was, LastUsed: lastUsed(dir)})
	}
	sort.Slice(cands, func(i, j int) bool { return cands[i].LastUsed.After(cands[j].LastUsed) })
	return cands, total, nil
}

// lastUsed approximates a stored project's last activity: the generated
// Dockerfile is re-staged on every develop, so its mtime is the best cheap
// signal; the path record's mtime (creation) is the floor.
func lastUsed(projectDir string) time.Time {
	var t time.Time
	for _, f := range []string{
		filepath.Join(projectDir, "context", "Dockerfile.generated"),
		filepath.Join(projectDir, "path"),
	} {
		if fi, err := os.Stat(f); err == nil && fi.ModTime().After(t) {
			t = fi.ModTime()
		}
	}
	return t
}
