// Package project derives byre's per-project identity and on-disk locations.
//
// project_id = sha256(canonical absolute path), truncated. It is a *naming*
// device only (Docker-safe), never a caching key — Docker owns caching.
package project

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// hashLen is how many hex chars of the sha256 disambiguate a project. The hash
// is only a uniqueness suffix on a human-readable slug, so 6 (24 bits) is ample:
// a collision needs the same sanitized last-two path components AND the same 24
// bits, and even then it fails LOUDLY — Bootstrap checks the path record and
// errors before any state (image, volumes, config) is shared (see
// TestBootstrapDetectsCollision). Considered and declined bumping this
// (2026-07-17): the id keys the on-disk store and scoped volume names, so any
// length change silently orphans every existing project's state — a certain
// migration break traded against an already-fenced ~2^-24 corner. Do not
// change without an id-migration story.
const hashLen = 6

// maxSlug caps the readable slug length so Docker object names stay reasonable.
const maxSlug = 40

// nonAlnum matches runs of characters not allowed in a Docker name component.
var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

// Canonicalize resolves a project path to a stable absolute form: symlinks
// resolved, cleaned, no trailing slash. Two paths denoting the same directory
// canonicalize identically, so they yield the same id.
func Canonicalize(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	// Resolve symlinks when the path exists; fall back to the cleaned absolute
	// path otherwise, so an id can still be computed for a not-yet-created dir.
	if resolved, rerr := filepath.EvalSymlinks(abs); rerr == nil {
		abs = resolved
	}
	abs = filepath.Clean(abs)
	if abs != string(filepath.Separator) {
		abs = strings.TrimRight(abs, string(filepath.Separator))
	}
	return abs, nil
}

// ID returns the project identity: a readable slug of the last two path
// components plus a short hash of the canonical path for uniqueness, e.g.
// /Users/me/dev/byre -> "byre-dev-0877d7". The "byre-" prefix that callers add
// makes the final Docker name valid regardless of the slug content.
func ID(path string) (string, error) {
	canon, err := Canonicalize(path)
	if err != nil {
		return "", err
	}
	return idFromCanonical(canon), nil
}

// idFromCanonical builds the id from an already-canonicalized path, so the
// recorded path and the id derive from the same canonicalization.
func idFromCanonical(canon string) string {
	leaf := sanitize(filepath.Base(canon))
	parent := sanitize(filepath.Base(filepath.Dir(canon)))

	parts := make([]string, 0, 2)
	if leaf != "" {
		parts = append(parts, leaf)
	}
	if parent != "" {
		parts = append(parts, parent)
	}
	slug := strings.Join(parts, "-")
	if len(slug) > maxSlug {
		slug = strings.Trim(slug[:maxSlug], "-")
	}
	if slug == "" {
		slug = "project"
	}

	sum := sha256.Sum256([]byte(canon))
	return slug + "-" + hex.EncodeToString(sum[:])[:hashLen]
}

// sanitize lowercases a path component and reduces it to Docker-name-safe
// characters ([a-z0-9], runs of anything else collapse to a single dash).
func sanitize(s string) string {
	return strings.Trim(nonAlnum.ReplaceAllString(strings.ToLower(s), "-"), "-")
}

// idRe is the shape every generated id has: a non-empty Docker-safe slug,
// then the 6-hex path-hash suffix. Hyphens only ever separate non-empty
// alnum runs -- sanitize collapses and trims them, so a generated slug
// never carries adjacent or trailing hyphens. Kept next to idFromCanonical
// so the grammar and the generator can't drift.
var idRe = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*-[0-9a-f]{6}$`)

// ValidID reports whether s has the shape of a byre project id. Commands
// that take an id from the user (e.g. `byre rehome <old-id>`) check it
// before using the id as a store path component or volume-name prefix — a
// malformed id can't have been generated by byre, so refusing it loses
// nothing and keeps garbage out of filepath.Join.
func ValidID(s string) bool {
	return idRe.MatchString(s)
}

// Home returns the byre home directory (~/.byre), overridable via BYRE_HOME
// (used by tests and unusual setups).
func Home() (string, error) {
	if h := os.Getenv("BYRE_HOME"); h != "" {
		return h, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".byre"), nil
}

// Paths holds the on-disk locations byre uses for one project.
//
// The build context is a subdirectory so the path record and lock file (which
// live directly under Dir) are not sent to the engine as build context.
//
// Worktree inheritance (docs/adr/0009-worktrees-inherit-project-identity.md):
// a linked git worktree
// inherits the MAIN worktree's identity — the id-keyed fields (ID/Canonical/
// Dir/ContextDir/PathRecord/LockFile) all derive from the project identity (main
// worktree) path, so config, volumes, and the image are shared. Only the
// strictly-local bits stay per-worktree: WorkDir (bound at /workspace) and
// WorktreeID (the container name + per-worktree label, so two worktrees can run
// at once). For a plain project WorkDir == Canonical and WorktreeID == ID.
type Paths struct {
	ID         string // project id, shared across worktrees (config/volumes/image identity)
	Canonical  string // canonical project dir (main worktree; == WorkDir when not a worktree)
	WorkDir    string // canonical dir bound at /workspace (the worktree; == Canonical when not a worktree)
	Home       string // ~/.byre
	Dir        string // ~/.byre/projects/<ID>
	ContextDir string // ~/.byre/projects/<ID>/context  (docker build context)
	Dockerfile string // <ContextDir>/Dockerfile.generated
	PathRecord string // ~/.byre/projects/<ID>/path
	LockFile   string // ~/.byre/projects/<ID>/lock

	IsWorktree   bool   // WorkDir is a linked git worktree of Canonical
	WorktreeID   string // per-worktree id from WorkDir (container name + workdir label; == ID when not a worktree)
	CommonGitDir string // git common dir: bind mount TARGET (in-box path git pointers resolve against); "" when not a worktree
	// CommonGitDirHost is the bind mount SOURCE for CommonGitDir — the same
	// directory, symlink-resolved. It differs from CommonGitDir only when the
	// git-recorded path contains symlinks; resolving the source closes a
	// check-to-mount retarget race (see worktree.go). "" when not a worktree.
	CommonGitDirHost string
}

// Resolve computes the id and on-disk paths for a project directory. When
// projectDir is a linked git worktree, the id-keyed paths resolve from the main
// worktree's path (so the worktree inherits the repo's config/volumes/image),
// while WorkDir/WorktreeID/CommonGitDir capture the per-worktree side.
func Resolve(projectDir string) (Paths, error) {
	work, err := Canonicalize(projectDir)
	if err != nil {
		return Paths{}, err
	}
	home, err := Home()
	if err != nil {
		return Paths{}, err
	}

	// Identity anchor: a linked worktree inherits the main worktree's path.
	identity := work
	var isWT bool
	var commonGitDir, commonGitDirHost string
	if info, ok, derr := detectWorktree(work); derr != nil {
		return Paths{}, derr
	} else if ok {
		identity, isWT = info.mainDir, true
		commonGitDir, commonGitDirHost = info.commonGitDir, info.commonGitDirHost
	}

	id := idFromCanonical(identity)
	worktreeID := id
	if isWT {
		worktreeID = idFromCanonical(work)
	}
	dir := filepath.Join(home, "projects", id)
	ctx := filepath.Join(dir, "context")
	return Paths{
		ID:               id,
		Canonical:        identity,
		WorkDir:          work,
		Home:             home,
		Dir:              dir,
		ContextDir:       ctx,
		Dockerfile:       filepath.Join(ctx, "Dockerfile.generated"),
		PathRecord:       filepath.Join(dir, "path"),
		LockFile:         filepath.Join(dir, "lock"),
		IsWorktree:       isWT,
		WorktreeID:       worktreeID,
		CommonGitDir:     commonGitDir,
		CommonGitDirHost: commonGitDirHost,
	}, nil
}

// Bootstrap ensures ~/.byre/projects/<id>/ exists and records the canonical
// path. If a different path is already recorded under the same id, that is a
// hash collision and Bootstrap returns an error rather than silently reusing
// another project's image and volumes.
func (p Paths) Bootstrap() error {
	if err := os.MkdirAll(p.ContextDir, 0o755); err != nil {
		return err
	}
	recorded, err := p.checkRecord()
	if err != nil {
		return err
	}
	if !recorded {
		return os.WriteFile(p.PathRecord, []byte(p.Canonical+"\n"), 0o644)
	}
	return nil
}

// ValidateExisting is Bootstrap's read-only half: the same collision check
// against an existing path record, creating nothing — no directory, no
// record. Inspection commands (dockerfile, dockerrun, ejectfirewall) use it
// so "show me what you would do" never enrolls a project in ~/.byre/projects.
func (p Paths) ValidateExisting() error {
	_, err := p.checkRecord()
	return err
}

// checkRecord reads the path record if present and errors on an id collision
// (a record naming a different canonical path). recorded reports whether a
// valid record already exists; a missing record is not an error.
func (p Paths) checkRecord() (recorded bool, err error) {
	existing, err := os.ReadFile(p.PathRecord)
	switch {
	case err == nil:
		// Trim only the record's trailing newline — Unix paths may legitimately
		// end in spaces, so TrimSpace would cause false collisions.
		if rec := strings.TrimSuffix(string(existing), "\n"); rec != p.Canonical {
			return true, fmt.Errorf("project id %s collision: recorded path %q != current %q", p.ID, rec, p.Canonical)
		}
		return true, nil
	case errors.Is(err, os.ErrNotExist):
		return false, nil
	default:
		return false, err
	}
}
