package packages

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Pack emits the distribution manifest for a LOCAL package (D5c): the primary
// file's body with a normalized [package] header and a generated, exhaustive
// [[package.files]] list -- every file in the package directory except the
// primary itself, hashes computed from disk. Returns the manifest bytes and
// the package digest (D5f) over them.
//
// Pack refuses rather than inventing identity: the author must have declared
// a qualified id (D1d), a version, and a requires_byre constraint in
// [package] -- those are publishing decisions. kind and package_api are
// mechanical and filled in.
func Pack(ent *Entry) ([]byte, string, error) {
	if ent.Provenance != ProvLocal {
		return nil, "", fmt.Errorf("pack works on local packages; %q is %s (fork it first)", ent.ID, ent.Provenance)
	}
	if ent.Dir == "" {
		return nil, "", fmt.Errorf("package %q has no directory", ent.ID)
	}
	raw, err := ent.ReadPrimary()
	if err != nil {
		return nil, "", err
	}
	m, _, err := ParseManifestCore(raw)
	if err != nil {
		return nil, "", err
	}
	var missing []string
	if m.ID == "" || IsBare(m.ID) {
		missing = append(missing, `a qualified id (id = "owner/name")`)
	}
	if m.Version == "" {
		missing = append(missing, `a version (version = "1.0.0")`)
	}
	if m.RequiresByre == "" {
		missing = append(missing, `a byre constraint (requires_byre = ">=0.2.0")`)
	}
	if len(missing) > 0 {
		return nil, "", fmt.Errorf("declare in [package] before packing: %s", strings.Join(missing, "; "))
	}
	if m.ID != ent.ID {
		return nil, "", fmt.Errorf("declared id %q does not match catalog id %q", m.ID, ent.ID)
	}

	entries, err := enumeratePayloads(ent.Dir, ent.Primary)
	if err != nil {
		return nil, "", err
	}
	if err := ValidateFilesList(entries, ent.Primary); err != nil {
		return nil, "", err
	}

	// Normalized header: author-declared identity + mechanical fields.
	var hdr strings.Builder
	hdr.WriteString("[package]\n")
	fmt.Fprintf(&hdr, "id = %q\n", m.ID)
	fmt.Fprintf(&hdr, "version = %q\n", m.Version)
	fmt.Fprintf(&hdr, "kind = %q\n", ent.Kind)
	fmt.Fprintf(&hdr, "package_api = %d\n", PackageAPI)
	fmt.Fprintf(&hdr, "requires_byre = %q\n", m.RequiresByre)
	if m.Description != "" {
		fmt.Fprintf(&hdr, "description = %q\n", m.Description)
	}
	hdr.WriteString("\n")

	body := strings.TrimLeft(string(StripPackageTable(raw)), "\n")

	var files strings.Builder
	if len(entries) > 0 {
		files.WriteString("\n# Distribution payload list -- generated by `byre " + string(ent.Kind) + " pack`.\n")
		for _, e := range entries {
			files.WriteString("[[package.files]]\n")
			fmt.Fprintf(&files, "src = %q\n", e.Src)
			fmt.Fprintf(&files, "dest = %q\n", e.Dest)
			fmt.Fprintf(&files, "sha256 = %q\n", e.SHA256)
			if e.Executable {
				files.WriteString("executable = true\n")
			}
			files.WriteString("\n")
		}
	}

	manifest := []byte(hdr.String() + body + files.String())
	digest := PackageDigest(manifest, RecordsFromEntries(entries))
	return manifest, digest, nil
}

// enumeratePayloads walks dir and returns one FileEntry per regular file
// (primary excluded), src == dest (package-relative), sorted. Symlinks are
// refused: a payload that points elsewhere is a trap, not a file.
func enumeratePayloads(dir, primary string) ([]FileEntry, error) {
	var out []FileEntry
	err := filepath.Walk(dir, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(dir, p)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("%s is a symlink; packages carry files, not links", rel)
		}
		if info.IsDir() {
			return nil
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("%s is not a regular file", rel)
		}
		if rel == primary {
			return nil
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		out = append(out, FileEntry{
			Src:        rel,
			Dest:       rel,
			SHA256:     HashBytes(b),
			Executable: info.Mode().Perm()&0o111 != 0,
		})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Dest < out[j].Dest })
	return out, nil
}
